### ISSUE TITLE
Can't delete a key

### ISSUE THREAD

**Issue by joseluis** [mehcode/config-rs#108]
I'm trying to update the configuration by deleting / removing a key and I can't find an easy way. I hope there's a way, though.

I found neither set nor merge are responding the way I was expecting. Is there any way you can recommend, or maybe implement a delete method?

Thanks

**Comment by joseluis** [comment]
I tried to implement a `del` method in `Config`, as far as my limited understanding of how this crate works, but doesn't seem to do anything. I leave it here in case someone else wants to try:

`config.rs`
```rust
    pub fn del(&mut self, key: &str) -> Result<&mut Config> {
        // Parse the key into a path expression
        let expr: path::Expression = key.to_lowercase().parse()?;

        match self.kind {
            ConfigKind::Mutable {
                ref mut overrides, ..
            } => {
                overrides.remove(&expr);
            }

            ConfigKind::Frozen => return Err(ConfigError::Frozen),
        }
        self.refresh()
    }
```

**Comment by matthiasbeyer** [comment]
It does not work, I guess, because the `refresh()` method re-reads the objects from their source.

So you basically are doing this:

1. Read the Config
1. Delete a key
1. Read the Config

And 3 does overwrite 2.

**Comment by matthiasbeyer** [comment]
Were you able to work around that issue?

I'll close this for now, feel free to reopen if your issue still exists!
