### ISSUE TITLE
Does `Config::new()` returns the same as `Config::default()`?

### ISSUE THREAD

**Issue by updogliu** [mehcode/config-rs#113]
Does `Config::new()` returns (effectively) the same as `Config::default()`? If not, better to document how are they different. If so, should `Config::new()` just delegate to `Config::default()` in the implementation?

**Comment by mehcode** [comment]
The automatic implementation of `Default` should be removed (I would move `::new` to a manual Default impl and delegate to the Default impl in new) and this should be fixed. Currently `Config::default()` can't be used if you want to rely on a `#[serde(default)]` annotation.

**Comment by updogliu** [comment]
Sounds good. I think I can draft a PR.
