### ISSUE TITLE
error: cannot find derive macro `Deserialize` in this scope

### ISSUE THREAD

**Issue by ogonbat** [mehcode/config-rs#121]
Hi All

I have a simple rust project workspace, on that workspace I have to crates
one is service that is a binary project and another is configs that is a lib project
in the configs project i have added as a dependecies the following crates
`[dependencies]
config = "0.9"
serde_derive = "^1.0.8"
serde = { version = "^1.0.8", features = ["derive"] }`

the lib.rs file on configs project contain the following code

`use config::{Config, File};

#[derive(Debug, Deserialize)]
struct Peer {
    name: String,
}

#[derive(Debug, Deserialize)]
pub struct Settings {
    peers: Vec<Peer>,
}

impl Settings {
    fn new() {
        let mut s = Config::new();
        s.merge(File::with_name("conf/system"));
        println!("peers: {:?}", s.get_array("system.peers"));
        s.try_into();
    }
}
`

in service main.rs file i call the lib configs

`use config::Settings;

fn main() {
    let settings = Settings::new();
    println!("Hello, world!");
}`

When i call the 'cargo build' command i get this error

`       Fresh unicode-xid v0.2.0
       Fresh autocfg v0.1.6
       Fresh serde v0.8.23
       Fresh version_check v0.1.5
       Fresh lazy_static v1.4.0
       Fresh regex-syntax v0.6.12
       Fresh lazy_static v0.2.11
       Fresh itoa v0.4.4
       Fresh linked-hash-map v0.5.2
       Fresh rust-ini v0.13.0
       Fresh serde_test v0.8.23
       Fresh proc-macro2 v1.0.5
       Fresh memchr v2.2.1
       Fresh thread_local v0.3.6
       Fresh yaml-rust v0.4.3
       Fresh quote v1.0.2
       Fresh aho-corasick v0.7.6
       Fresh linked-hash-map v0.3.0
       Fresh ryu v1.0.1
       Fresh syn v1.0.5
       Fresh num-traits v0.2.8
       Fresh regex v1.3.1
       Fresh nom v4.2.3
       Fresh serde_derive v1.0.101
       Fresh num-traits v0.1.43
       Fresh serde v1.0.101
       Fresh serde-hjson v0.8.2
       Fresh serde_json v1.0.41
       Fresh toml v0.4.10
       Fresh config v0.9.3
   Compiling configs v0.1.0 (/Users/xxx/xxx/xxx/configs)
     Running `rustc --edition=2018 --crate-name configs configs/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=d575a0335de2dec1 -C extra-filename=-d575a0335de2dec1 --out-dir /Users/xxx/xxx/xxx/target/debug/deps -C incremental=/Users/xxx/xxxx/xxx/target/debug/incremental -L dependency=/Users/xxx/xxx/xxx/target/debug/deps --extern config=/Users/xxx/xxx/xxx/target/debug/deps/libconfig-a97efa5681c2e470.rmeta --extern serde=/Users/xxx/xxx/xxx/target/debug/deps/libserde-ccc34701dbb312c1.rmeta --extern serde_derive=/Users/xxx/xxx/jackalope/target/debug/deps/libserde_derive-6610f6c659519371.dylib`
error: cannot find derive macro `Deserialize` in this scope
  --> configs/src/lib.rs:13:17
   |
13 | #[derive(Debug, Deserialize)]
   |                 ^^^^^^^^^^^

error: cannot find derive macro `Deserialize` in this scope
  --> configs/src/lib.rs:18:17
   |
18 | #[derive(Debug, Deserialize)]
   |                 ^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `configs`.

Process finished with exit code 101
`

Sorry in advance if the question is stupid, I'm new in RUST

**Comment by KoltesDigital** [comment]
Indeed, `Deserialize` is provided by `serde`.

```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Peer {
    name: String,
}
```

**Comment by KoltesDigital** [comment]
Working code:

setttings.rs

```rust
use config::{Config, ConfigError, File};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Peer {
	name: String,
}

#[derive(Debug, Deserialize)]
pub struct Settings {
	peers: Vec<Peer>,
}

impl Settings {
	pub fn new() -> Result<Self, ConfigError> {
		let mut s = Config::new();
		s.merge(File::with_name("config.yml"));
		println!("peers: {:?}", s.get_array("peers"));
		s.try_into()
	}
}
```

main.rs

```rust
mod settings;

use settings::Settings;

fn main() {
	let s = Settings::new();
	println!("{:?}", s);
}
```

Output:

```
peers: Ok([Value { origin: None, kind: Table({"name": Value { origin: None, kind: String("...") }}) }])
Ok(Settings { peers: [Peer { name: "..." }] })
```

**Comment by matthiasbeyer** [comment]
This issue seems to be solved. Can someone close it please?
