### ISSUE TITLE
Enable toml dependency only via feature flag

### ISSUE THREAD

**Issue by jcrevier** [mehcode/config-rs#127]
At the moment, it seems that its not possible to only pull in the toml dependency. There are separate feature flags for each of the other configuration types. For parity, there should be a separate feature flag for toml as well.

**Comment by tmccombs** [comment]
toml is an optional dependency, isn't this already possible?

**Comment by jcrevier** [comment]
Yes, you're correct. I didn't realize I had to specify `default-features = false` and also specify `features = ["toml"]`. Sorry for the noise.
