### ISSUE TITLE
Deprecation warning in old version lazy_static! use in various examples

### ISSUE THREAD

**Issue by eisterman** [mehcode/config-rs#135]
In various examples the `lazy_static!` macro from lazy_static v1.0 crate generate the deprecation warning
```warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred```

The actual version of lazy_static is v1.4 and I'm advising to upgrade the create.

**Comment by matthiasbeyer** [comment]
Is this still relevant?

**Comment by matthiasbeyer** [comment]
So, I am not getting any warnings with rustc 1.50.0, so I'll close this now. Feel free to reopen if this is still an issue.
