### ISSUE TITLE
log::Level not deserializable in 0.10.0

### ISSUE THREAD

**Issue by Yatekii** [mehcode/config-rs#136]
I use [log::Level](https://docs.rs/log/0.4.10/log/enum.Level.html) in my config structs and this works great with config 0.9.0 and the serde feature enabled on the log crate (v 0.4.0).

In version 0.10.0 I get enum `Level does not have variant constructor Error', src/config/mod.rs:7:37` for every variant of the `Level` enum I try.

**Comment by saethlin** [comment]
`ERROR` will work.

This is a pretty serious issue for me too, there was a _lot_ of breakage in 0.10 around case-sensitivity.

**Comment by matthiasbeyer** [comment]
Do I understand correctly that this is only due to case sensitivity, but there is no real bug here?
If that's the case, I'd close this issue.

**Comment by Yatekii** [comment]
I consinder this a bug tbh.

a) Why would it be case sensitive?
b) Why make this change? Enum variants are CapsCamelCase and not SCREAM_CASE.

But ofc. It is your choice :)

**Comment by matthiasbeyer** [comment]
Hm. I'm not sure that's a bug in config-rs, is it? :confused:

**Comment by Yatekii** [comment]
Define "bug". It is something in config-rs. https://docs.rs/log/0.4.14/src/log/lib.rs.html#513 log itself can parse it from any case.

**Comment by matthiasbeyer** [comment]
Ok cool, I'll have a look!

**Comment by matthiasbeyer** [comment]
I am closing this, after #188 was merged and I _think_ this issue is resolved. Feel free to comment and I'll reopen if necessary.
