### ISSUE TITLE
Git repository is missing tags

### ISSUE THREAD

**Issue by alerque** [mehcode/config-rs#139]
Tags since 0.9.3 are missing. These are really useful to know what is in which releases when browsing code or seeing what changed.

**Comment by matthiasbeyer** [comment]
Hi.
I'm the current maintainer.

I also feel bad about this, but it seems there's nothing we can do. The original maintainer does not seem to have them... so this is all we've got.

Sorry for not being able to help here.
I'm gonna close this as unresolved ("not planned").
