### ISSUE TITLE
Provide a way to warn about unused keys

### ISSUE THREAD

**Issue by dtolnay** [mehcode/config-rs#14]
If I source a config file where the user has a typo in a key, I want to be able to warn or error rather than silently ignore that entry.

Possibly relevant - this is the approach that Cargo will be using to warn about unused entries in Cargo.toml https://github.com/dtolnay/serde-ignored.

**Comment by mehcode** [comment]
Perhaps both this and #13 can do something with the schema idea from #7 

```rust
#[config(strict = true, unrecognized = "warn")]
struct AppConfig { ... }
```

 - **strict** - enforce a stricter type identity (don't auto-coerce)
 - **ununrecognized = warn** - warn for any keys that are not specified in the schema when loading

**Comment by dtolnay** [comment]
One approach that would be less work and that I would find more useful would be to expose a unit struct config::Deserializer that implements Serde's Deserializer trait. That way this crate would compose well with other crates that deal with generic deserializers, including serde-ignored.

```rust
// Build a set of paths to the unused elements.
let mut unused = Set::new();

// Deserialize with a callback that inserts unused keys into the set.
let c: MyConfig = serde_ignored::deserialize(config::Deserializer, |path| {
    unused.insert(path.to_string());
}).unwrap();

// Deserialized as normal.
println!("{:?}", c);

// Application-specific logic to warn or error on unused keys.
for k in unused {
    println!("unused configuration key: {}", k);
}
```

**Comment by mehcode** [comment]
That API looks lovely. Agreed.

**Comment by mehcode** [comment]
This should be able to work now on master.

**Comment by jpmckinney** [comment]
I'm struggling to figure out how this is supposed to work in the latest version of config.

Can an example be provided?
