### ISSUE TITLE
Function misnamed, should corrrelate to type

### ISSUE THREAD

**Issue by alerque** [mehcode/config-rs#140]
Rust has types for both `str` and `String`. There are tons of functions in *std* and other crates related to the two, `as_str()`, `as_string()`, `from_string()`, `to_string()`, `to_str()`, etc.

This function is cross wired:

https://github.com/mehcode/config-rs/blob/2c0b201055be60ec45e258adcc6c4b6e01bcd627/src/config.rs#L172

It should either be named `get_string()` or return a `str` but not switch them out! Perhaps there should be two functions, one for each...

**Comment by matthiasbeyer** [comment]
Would you submit a patch for that change? I'd merge an appropriate patch for this.
