### ISSUE TITLE
Using valid json produces error

### ISSUE THREAD

**Issue by andy5995** [mehcode/config-rs#145]
Using v0.10.1

I get this error:

```invalid type: sequence, expected a string for key `WASTE` in config_test.json'```

The contents of my json file:

```
{
  "WASTE": ["example_dir1", "example_dir2"]
}
```

My goal is to have multiple items for WASTE, and assign each to a linked list or Vector. That's why I'm using one key for that configuration option.

I tried using .toml format, but got the same error.

```WASTE = ["example_dir1",  "example_dir2"]```

**Comment by szarykott** [comment]
I am not a pro with this crate, but this functionality should be covered, it is even tested. Seems like you are trying to convert json arrays to a string, by looking at error message. Can you provide rust code sample that is throwing this error?

**Comment by andy5995** [comment]
Hmmm, that was a while ago. I would have used one of the provided examples to start with.

> I am not a pro with this crate, but this functionality should be covered, it is even tested.

Where's the test?

**Comment by szarykott** [comment]
For json it is here : https://github.com/mehcode/config-rs/blob/master/tests/file_json.rs

In Settings there is a Vec, is this your use case?

**Comment by andy5995** [comment]
It's really a dead issue for me, but thank you for the follow-up, @szarykott . I've been using the [configster library](https://lib.rs/crates/configster) for a while now.
