### ISSUE TITLE
config-rs broken since rust 1.48

### ISSUE THREAD

**Issue by dessalines** [mehcode/config-rs#158]
We're trying to use `config-rs` using the latest rust `nightly-1.49-0`, and we're getting:

```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<std::string::String, value::Value>` uninitialized
, which is invalid', /home/tyler/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/
mem/mod.rs:659:9
```

I see this is also failing on your travis build too:

https://travis-ci.org/github/mehcode/config-rs/jobs/734764347#L291

cc @Nutomic

**Comment by joelgallant** [comment]
This is an upstream / rustc bug, no?

**Comment by dessalines** [comment]
Don't think so: https://travis-ci.org/github/mehcode/config-rs/jobs/734764347#L291

**Comment by dessalines** [comment]
config-rs is now broken on rust `1.48.0`.

**Comment by joelgallant** [comment]
A quick note - this is a test failure, originating in serde_hjson. Error is bubbling up from [this line](https://github.com/mehcode/config-rs/blob/master/src/file/format/hjson.rs#L13).

**Comment by endeav0r** [comment]
This appears to be the offending line: https://github.com/contain-rs/linked-hash-map/blob/master/src/lib.rs#L174

`linked-hash-map` appears to be an old crate, with unsafe behavior. Allocated this type without initializing it, in this unsafe code, is what's throwing these errors. `linked-hash-map` is being used by `yaml-rust`, which is being used by `config-rs`. `yaml-rust` is maybe trying to replace `linked-hash-map` ( https://github.com/chyh1990/yaml-rust/pull/157 ), which would most likely solve this issue.

Until then, I can't run my projects which rely on `config-rs` to parse yaml configurations :(.

**Comment by iruizr7** [comment]
This is happening now on last stable.

**Comment by martinellison** [comment]
I am getting this too.

**Comment by dessalines** [comment]
One possibility would be for config-rs to use feature flags, so that the upstream broken `yaml-rust` library can be ignored entirely.

**Comment by mehcode** [comment]
`config` does actually, except they're all by-default enabled

```
config = { version = "*", default-features = false, features = [ "json", "toml" ] }
```

**Comment by dessalines** [comment]
We are using `config = { version = "0.10.1", default-features = false, features = ["hjson"] }`, yet the build has still been failing since 1.48.0

**Comment by dessalines** [comment]
Since yaml-rust hasn't worked for the past two months, how about using https://github.com/dtolnay/serde-yaml as the yaml library instead?

**Comment by Nutomic** [comment]
We were wrong about this, the problem isnt caused by yaml-rust but by hjson-rust itself. Here is the issue with some possible solutions:

https://github.com/hjson/hjson-rust/issues/23#issuecomment-775520018

**Comment by dessalines** [comment]
Seems both libraries have the same ultimate problem: they're both using `linked-hash-map`, which is abandoned. They both need PRs to update to use the new https://github.com/kyren/hashlink library, which is maintained. Unfortunately yaml-rust's maintainers also seem to be unresponsive, as there's been a PR to merge hashlink that hasn't been looked at in months. Maybe hjson's maintainer will be more responsive.
