### ISSUE TITLE
128-bit integers are not supported

### ISSUE THREAD

**Issue by nagisa** [mehcode/config-rs#161]
Trying to `Config::get` a structure that contains u128 fields will fail with an error from serde.

> u128 is not supported

---

config-rs should override the u128 and i128 methods to support these integers.

**Comment by matthiasbeyer** [comment]
I guess this means that `Deserializer::deserialize_u128` and similar functions must be implemented on `Value`, right? Also, the internal `ValueKind` type must be able to hold a 128 bit sized integer.

Would you like to implement this in a PR?

**Comment by matthiasbeyer** [comment]
I just added a [patch](https://git.sr.ht/~matthiasbeyer/config-rs-maint/commit/116b860bc40e283518243139fe54ac5a0be8c6d6) to config-rs-maint (not in master yet) that adds support for 128bit integers (signed).

Would you like to contribute tests for this patch?

**Comment by nagisa** [comment]
Hi, I'll see if I can make time to contribute some tests. Not super confident I'll be able to, though.
