### ISSUE TITLE
Value::try_into makes use of TryInto difficult

### ISSUE THREAD

**Issue by djmitche** [mehcode/config-rs#162]
I'd like to write some conversions for my own structs from instances of Value, and `std::convert::TryFrom` / `TryInto` are good choices for this.  However, the existence of a `try_into` method on the struct, unrelated to these traits, shadows the trait method.

Could the `try_into` method be renamed into `try_deserialize` or something of the sort?

**Comment by matthiasbeyer** [comment]
IMO, the `try_from` function should be reimplemented using the `TryFrom` trait anyways.

I think this is a good idea!

**Comment by matthiasbeyer** [comment]
Fixed in [config-rs-maint](https://git.sr.ht/~matthiasbeyer/config-rs-maint/) as of [master def3702fac13605af303b8319af15943cc7ff8e5](https://git.sr.ht/~matthiasbeyer/config-rs-maint/commit/def3702fac13605af303b8319af15943cc7ff8e5).

**Comment by conradludgate** [comment]
Sadly I don't think it's possible to implement it using TryFrom for all T because it conflicts.

I'm not _quite_ sure what with, but I think it's because a type could implement `From<Value>` and `Deserialize` individually downstream and that would have conflicting implementations

**Comment by conradludgate** [comment]
Should we just go with `try_deserialize()` for now?

**Comment by djmitche** [comment]
that sounds good to me :)

I'm confused, though, because it looks like @matthiasbeyer already did this?

**Comment by conradludgate** [comment]
> I'm confused, though, because it looks like @matthiasbeyer already did this?

Looking through their old maint fork, they only had this
https://git.sr.ht/~matthiasbeyer/config-rs-maint/tree/master/item/src/value.rs#L154. No TryFrom that I can find

**Comment by matthiasbeyer** [comment]
Yeah I even tried to implement the `TryInto` trait, but it was not possible when I tried... But having a function named `try_into()` is counter-intuitive, because it suggestes that the trait is there... which it is not. So I guess `try_deserialize()` it is, right?

**Comment by conradludgate** [comment]
I would say that's a consensus reached

**Comment by danieleades** [comment]
looks like this is already merged. can this be closed?

**Comment by matthiasbeyer** [comment]
Yes! Thanks for pinging me!
