### ISSUE TITLE
Edgecase: Only signed integers (64 bit) are supported?

### ISSUE THREAD

**Issue by matthiasbeyer** [mehcode/config-rs#167]
As far as I can see, only i64 are supported right now by this crate, am I right?

```
ValueKind::Integer(i64)
```

If someone wants to store a `u64`, they will run into an error, because we're casting `u64` to `i64`. This is most likely not a problem for any real-world configuration file, but should be fixed anyways.
Especially because #161 wants 128 bit integer support.

**Comment by jaskij** [comment]
Since #178 is merged, shouldn't this be closed? Or is there something else that needs to be done?

**Comment by matthiasbeyer** [comment]
Whoopsi, you are right! :tada: :laughing:
