### ISSUE TITLE
Consider remove global state

### ISSUE THREAD

**Issue by dtolnay** [mehcode/config-rs#17]
Global mutable state is hard (see #9) and doesn't seem worthwhile to me in this case. Have you considered exposing only the config::Config::get/set API rather than global config::get/set? Are there any use cases that you think would be difficult to express using config::Config rather than global?

**Comment by mehcode** [comment]
From [Viper](https://github.com/spf13/viper#viper-or-vipers)
>  Viper comes ready to use out of the box. There is no configuration or initialization needed to begin using Viper. Since most applications will want to use a single central repository for their configuration, the viper package provides this. It is similar to a singleton.

> You can also create many different vipers for use in your application. Each will have it’s own unique set of configurations and values. Each can read from a different config file, key value store, etc. All of the functions that viper package supports are mirrored as methods on a viper.

---

The key point for me is that a single (essentially global) configuration is the default state of affairs for the vast majority of applications. Needing to have 2 different pools of configuration is a strange requirement.

I feel the user shouldn't be required to manage the access to a configuration instance when we could do that for them.

With that said, the primary type of application I'll personally be building are web applications and I can do the following in Rocket so if we remove the global interface it won't bother me. We could always add it back later if there is demand and it's harder to remove an API than add one.

```rust
#![feature(plugin)]
#![plugin(rocket_codegen)]

extern crate rocket;
extern crate config;

use rocket::State;
use config::Config;

#[get("/")]
fn index(c: State<Config>) -> String {
    format!("Debug: {}!", c.get_bool("debug"))
}

fn main() {
    let mut c = Config::new();
    // c.merge( ) [...]

    rocket::ignite()
        .manage(c)
        .mount("/", routes![index])
        .launch();
}
```

Props to @SergioBenitez for making DI here so simple.

---

In closing, I'm slightly for the global state but will go with what the community feels on this matter.

**Comment by tmccombs** [comment]
> Needing to have 2 different pools of configuration is a strange requirement.
The main use case I can think of is unit tests.  Having global configuration makes it more difficult to inject the configuration you want to test (especially if the config is frozen in one or more of the unit tests).

**Comment by mehcode** [comment]
A big plus for removing the global API is it'll make this library work on stable.

That's convinced me.

**Comment by mehcode** [comment]
Removed in ccae9b0

**Comment by tmccombs** [comment]
The global functionality could be moved into a separate crate.

**Comment by mehcode** [comment]
As of `0.4.1` the Config struct is `Sync + Send` and can be easily used with `lazy_static!`.

```rust
use std::sync::RwLock;
use config::Config;

lazy_static! {
    static ref CONFIG: RwLock<Config> = Default::default();
}
```

I figure since that's simple enough there isn't a good reason to complicate the story here or in another crate.
