### ISSUE TITLE
Environment::with_prefix() doesn't use custom separator.

### ISSUE THREAD

**Issue by lyuben-todorov** [mehcode/config-rs#173]
At https://github.com/mehcode/config-rs/blob/master/src/env.rs#L81
```rust
        let prefix_pattern = match self.prefix {
            Some(ref prefix) => Some(prefix.clone() + "_"),
            _ => None,
        };
```
"_" is appended by default. Shouldn't the custom separator be appended if it exists instead?

**Comment by matthiasbeyer** [comment]
Would you like to contribute a patch to fix this issue to [config-rs-maint](https://git.sr.ht/~matthiasbeyer/config-rs-maint/)?
