### ISSUE TITLE
Allow usage in stable channel

### ISSUE THREAD

**Issue by alem0lars-svcuser** [mehcode/config-rs#18]
Currently this library can't be used in the stable channel, due to `#[feature]`.

Is it possible to have a version of `config-rs` compatible with stable rust?

**Comment by mehcode** [comment]
The only reason for nightly is the global API. 

However there are talks to remove that. 
See https://github.com/mehcode/config-rs/issues/17

If we did, it'd become stable.

**Comment by alem0lars-svcuser** [comment]
Ok Thanks 👍

**Comment by mehcode** [comment]
Added with ccae9b09fa9d4650de3cf91013162a7277e46060

**Comment by alem0lars-svcuser** [comment]
@mehcode you are my super-hero :) thanks very much!
