### ISSUE TITLE
Remove ConfigKind::Frozen

### ISSUE THREAD

**Issue by szarykott** [mehcode/config-rs#194]
`ConfigKind::Frozen` is only used during reads, but is never explicitly set. Unless I am mistaken, this is a dead enum variant.

Removing it could move the library one step closer towards cleaner code and the "do not refresh at every source add" paradigm. It would also simplify API as a lot of methods would no longer need to return `Result`.

I must admit that my vision here is to be able to introduce (caution, buzzword) _a typestate pattern_ somehow within the library and this `ConfigKind::Frozen` enum violates it. Having it removed would move a lot of runtime errors to compilation time.

PS. if this suggestion is accepted, I can do a quick PR for it!

**Comment by matthiasbeyer** [comment]
I addressed this in #190 - but exactly the other way around - you're very much welcome to submit a patch for removing this! I was not sure which way was the correct way, but as you seem to have plans, feel free to submit your changes and replace #190 with something better! :laughing:

**Comment by szarykott** [comment]
I answered in the pull request but reposting here as well.

I'd vote against keeping Frozen Config state.

I have serious reasons to justify it and I do have a strong vision of how config should work. After all, I spent months designing my own library. I'd like to have some opinion on that though.

In my mind, there should be two separate structs (or in any other way compliant with "typestate"):

* one that represents the builder
* one that represents built config

The reason for it is simple - moving runtime errors that can happen with Frozen / Mutable state to compilation time. Simply speaking - make invalid state impossible thanks to the type system. It has a clear advantage of "it compiles, it most probably works", but at the same time it forbids adding new sources during program operations. However, if one keeps a reference to a builder somewhere it is always possible to reuse it. From my experience, it is not a problem to do so.

**Comment by matthiasbeyer** [comment]
> Simply speaking - make invalid state impossible thanks to the type system.

Yes, we should definitively move towards that.

**Comment by szarykott** [comment]
I take it as a good sign ;)

I guess the issue can be closed as soon as you merge #190 .

On my side I have a branch I'll try to create pull requests for with refactoring of Config / ConfigBuilder that was discussed.

**Comment by szarykott** [comment]
I am closing as #190 has been merged.
