### ISSUE TITLE
Allow explicit specification of file format

### ISSUE THREAD

**Issue by huy-vuong** [mehcode/config-rs#197]
As an alternative to #21, instead of picking up the file format from the file's file extension, it'd be nice to be able to explicitly specify "The format will be `${format}`.". This decouples the config file format from the name.

What I'm looking for is the ability to have a config file `/home/huy/.tabby` that happens to be a JSON file, but I don't want to have to name my file `/home/huy/.tabby.json`. In code, I'd like to be able to call something like:

```rust
let mut settings = config::Config::default();
settings.merge(
    config::File::from(
        PathBuf::from(shellexpand::tilde("~/.tabby").to_string()),
        config::FileFormat::Json,
    )
)?;
```

Is there a way to do this currently?

**Comment by huy-vuong** [comment]
Ah, nevermind. I figured it out. Sorry for the wasted issue.

---

For anyone who's curious:

```rust
let mut settings = config::Config::default();
settings.merge(
    config::File::with_name(&shellexpand::tilde("~/.tabby").to_string())
        .format(config::FileFormat::Json),
)?;
```

**Comment by matthiasbeyer** [comment]
Never mind, congrats on figuring it out! :tada: :+1:
