### ISSUE TITLE
Configuration refresh should rebuild the configuration from source metadata

### ISSUE THREAD

**Issue by mehcode** [mehcode/config-rs#20]
Currently it doesn't do a full rebuild for File sources. It should re-read the file contents.

This bears discussion though.

```rust
c.set("key", 5);
// c.refresh();

c.merge(File::with_name("Settings"));
// c.refresh();

c.set("key", 5);
// c.refresh();
```

See above. Currently a `.refresh` call is done automatically after any stack mutation. 

 - If we switch this to re-reading files it will definitely increase execution time of any `.set`'s
 - The `Envrionment` source should probably have a `delete` option (that deletes keys from the environment after reading). It wouldn't make any sense to re-load then.

It sounds like we a source needs to have its own frozen state. 

Any thoughts on API here?
 - Should sources be frozen by default?
 - Should sources have a `.freeze()` / `.live(true)`  method  when building them?

**Comment by dtolnay** [comment]
Please don't worry about or optimize for the execution time of `set`. If that is a bottleneck in someone's application, they are doing it wrong.

**Comment by mehcode** [comment]
Fair enough. The otherror questions still remain though.

**Comment by mehcode** [comment]
This is on master. `config.refresh()` will rebuild the config from the original sources. All that's needed for https://github.com/mehcode/config-rs/issues/19 is a way to watch the files for changes and call `.refresh()`. That could be done outside of this crate as well for now. I don't plan to add watching to 5.0 (but perhaps 6.0), there are enough changes.
