### ISSUE TITLE
Maybe the parse of path is wrong, for a workspace or multiple environments?

### ISSUE THREAD

**Issue by cangSDARM** [mehcode/config-rs#201]
## Version
config = "0.10.1"

## What happened
I have a workspace, and 2 different env(mode)

When I write some unit test files in the "backend" and try to read "config/xxx.toml" in the "test" mode, it always panics.

When I tried to run it in "prod" mode, it worked normally again.
Or if I only write a project instead of a workspace, then everything works fine and no errors occurred.

## What is my environment like
workspace:

```
- repo
  - backend
  - macros
  - thridpart
  - conf
    - test.toml
    - default.toml
```

environments:

- `prod`
- `test`

## What is my code/errors like
Here is my code (handler.rs) and error:

```rust
use config::Config as GConfig;

lazy_static! {
    pub static ref CONFIG: RwLock<GConfig> = RwLock::new(GConfig::default());
    pub static ref FLOT: RwLock<GConfig> = RwLock::new(GConfig::default());
}

fn load_config(config_of: &str) {
    CONFIG
        .write()
        .unwrap()
        .merge(config::File::with_name(config_of))
        .expect("Merge config");
}

pub fn product_config() -> RwLockReadGuard<'static, GConfig> {
    load_config("conf/default");

    CONFIG.read().expect("Read product conf")
}

#[cfg(test)]
mod test{
    pub fn test_config() -> RwLockReadGuard<'static, Config> {
        load_config("conf/test");

        CONFIG.read().expect("Read test conf")
    }
    
   #[test]
    fn test_load() {
        load_config("conf/test");  //paincked.
        //thread 'handler::test::test_load' panicked at 'Merge config: configuration file "conf/test" not found',

        match CONFIG.read() {
            Ok(_) => assert_eq!(1, 1),
            Err(_) => assert_eq!(2, 1),
        };
    }
}
```

**Comment by matthiasbeyer** [comment]
I'm not sure I understand what you mean.
What do you mean by

> in the "test" mode, it always panics

and

> When I tried to run it in "prod" mode, it worked normally again

? Do you mean `cargo test` vs `cargo build`?

**Comment by cangSDARM** [comment]
yes

**Comment by matthiasbeyer** [comment]
Well then, did you understand that `cargo test` actually _runs_ things, because it executes tests and `cargo build` does not, as it only produces a binary for you to execute?

**Comment by cangSDARM** [comment]
So, in a nutshell, how can I fix it?

**Comment by matthiasbeyer** [comment]
Read the file yourself, using `config::File::from_str` to merge it into your `Config` object.

**Comment by cangSDARM** [comment]
Well, I will try.
