### ISSUE TITLE
Automatic file format detection (just based on extension) for File source

### ISSUE THREAD

**Issue by mehcode** [mehcode/config-rs#21]
```
File::with_name("name");
```

^ Should attempt the basename and _all_ registered extensions when looking for a file. Fallback to an error message if the file is found and not of an expected type.

**Comment by DanielJoyce** [comment]
If a file_name is passed in with an extension, it should load exactly that format too.

File::with_name("name.json")

**Comment by mehcode** [comment]
Agreed
