### ISSUE TITLE
hierarchical-env example environment prefix not working for nested variables

### ISSUE THREAD

**Issue by sstubbs** [mehcode/config-rs#213]
Hi,

Perhaps I'm doing something wrong but nested variables don't seem to work for me with env prefix. In the example I expected APP_DATABASE_URL=testurl to change it but this does not seem to be the case. ADD_DEBUG works fine but not the nested structs.

**Comment by matthiasbeyer** [comment]
Hi, thanks for your report :+1: 

Can you give a code snippet that shows your usecase? Possibly in as a PR with a test even? Because from your message I'm not sure what exactly doesn't work!

**Comment by sstubbs** [comment]
Hi,

I'm sorry I've had a bit of time to look through the source code. I was not setting a separator. This actually works perfectly it was a mistake on my end.

**Comment by matthiasbeyer** [comment]
Awesome that you sorted it out, thanks for reporting back! :heart: :tada: :+1:
