### ISSUE TITLE
No longer compiling on rust 1.53

### ISSUE THREAD

**Issue by jdavidagudelo** [mehcode/config-rs#214]
After 1.53 update of rust compilation of config-rs does not work because the dependency `nom = "6"` which depends on `lexical-core  = 0.6.2` which is broken in rust 1.53.

`error[E0308]: mismatched types
  --> /home/user/.cargo/registry/src/github.com-hash/lexical-core-0.6.2/src/atof/algorithm/bhcomp.rs:62:24
   |
62 |     let bytes = bits / Limb::BITS;
   |                        ^^^^^^^^^^ expected `usize`, found `u32``

**Comment by matthiasbeyer** [comment]
I cannot reproduce, sorry. Can you re-try `cargo update` and then `cargo check` in your clone? `nom` came out in `6.2.0` yesterday, maybe that's what solved the issue?

**Comment by jdavidagudelo** [comment]
Indeed after running cargo update the problem is fixed. Thanks.

**Comment by matthiasbeyer** [comment]
You're welcome! Don't hesitate to open issues here if you encounter problems or if you have any questions!
