### ISSUE TITLE
Error when running binaries directly.

### ISSUE THREAD

**Issue by sagarnayak** [mehcode/config-rs#215]
When I was running the [glob](https://github.com/mehcode/config-rs/tree/master/examples/glob) example. it runs perfectly when I do a cargo run.

but when I go to the target directory and execute the .exe file then I get this error -

	thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "conf/debug.toml" not found', src\main.rs:13:52
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

any thoughts on why this is happening.  

I was thinking there is no way I can assign an env variable if I just run this executable in the live server. if I want to do an env assignment then I need to do `cargo run`. am I right?

**Comment by matthiasbeyer** [comment]
> any thoughts on why this is happening.

because you need to execute the binary from `/examples/glob/` so it can find the `conf` directory in `/examples/glob/conf` (in case of the `glob` example).

> I was thinking there is no way I can assign an env variable if I just run this executable in the live server. if I want to do an env assignment then I need to do cargo run. am I right?

I don't know what you mean by that.
You can define an env variable (in bash) just before the binary: `VARIABLE=value ./binary` to define the variable for that one instance of a program.

Does that answer your questions?

**Comment by sagarnayak** [comment]
I thought i can just take the .exe and run on any windows system without installing rust. But i think now i have to take the whole project so that the associated files will be there.
Or is there any other way to achieve this where everything is compiled into the executable ?

**Comment by matthiasbeyer** [comment]
You don't need rust installed of course. But if you can execute `cargo run` you have rust installed.

You need to have the associated files of the project, yes.

Why would you want a config file to be compiled into the executable? That makes no sense at all!

**Comment by sagarnayak** [comment]
so what I can do is pre-program the .exe to find the config files at a specified place. and then ship the config and .exe to the server. and execute it.

this will do the work. right? and I would not need the rust to install on the server at all.

**Comment by matthiasbeyer** [comment]
> so what I can do is pre-program the .exe to find the config files at a specified place. and then ship the config and .exe to the server. and execute it.

Yes, that is exactly what the `glob` example does, for example. It searches at `./conf/default.toml` (see [here](https://github.com/mehcode/config-rs/blob/master/examples/glob/src/main.rs#L13)).

No need to have rust installed except for building your sourcecode!

**Comment by matthiasbeyer** [comment]
I think this is resolved, so I'll close it.

Feel free to ping me if more questions arise! :+1: :smile:
