### ISSUE TITLE
Add examples on how to use the ConfigBuilder

### ISSUE THREAD

**Issue by AdheipSingh** [mehcode/config-rs#228]
Thanks for this library.
I am new to rust and was playing around with the examples to get started. 

Just encountered this warning on compilation
```
warning: use of deprecated associated function `config::Config::merge`: please use 'ConfigBuilder' instead
 --> src/main.rs:7:10
  |
7 |         .merge(config::File::with_name("Settings")).unwrap()
  |          ^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `config::Config::merge`: please use 'ConfigBuilder' instead
  --> src/main.rs:10:10
   |
10 |         .merge(config::Environment::with_prefix("APP")).unwrap();
   |          ^^^^^

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/simple`
{"priority": "32", "debug": "false", "key": "189rjfadoisfj8923fjio"}
```
Just wondering if the example can be updated to configBuilder. An explanation on the usage of configbuilder vs merge will helpful too.

**Comment by matthiasbeyer** [comment]
This (examples not using deprecated stuff anymore) is WIP in #223 !

An example would definitively be nice, so I'll leave this open.

**Comment by Davidprogram2** [comment]
what does this mean please?

**Comment by matthiasbeyer** [comment]
I just checked, the documentation for the `ConfigBuilder` type already includes an example, so there's nothing to do here actually. I'll close this now.
