### ISSUE TITLE
[Question] Can this be used as a dotfile?

### ISSUE THREAD

**Issue by alexhallam** [mehcode/config-rs#238]
I have a cli utility. I would like it to search for a users dotfile (aka `util.toml`) to find user preferences for the utility. 

The problem is that my utility is cross-platform (Windows, Mac, Linux). Think about possible locations for a config file across these Oses is challenging. 

Does this library `config-rs` solve this issue? 

Would I be able to tell a user where to put a config file, regardless of OS, and use this library to find it?

**Comment by matthiasbeyer** [comment]
No, finding the right path for you is not in scope of this library. You might want to look into the [directories](https://crates.io/crates/directories) crate for that.
