### ISSUE TITLE
JSON5 is not of a registered file format

### ISSUE THREAD

**Issue by lanceschi** [mehcode/config-rs#239]
Hello @mehcode,

thanks for the awesome lib, I'm only facing an issue with `JSON5` files. This is an example of the error message:
```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: configuration file "~/hello-world/config/default.json5" is not of a registered file format', src/main.rs:15:6
```

Here's the dependencies section in my Cargo.toml:
```toml
[dependencies]
config = "0.11"
```

This is the part of the code that is raising the error:
```rust
  let mut settings = Config::default();

  settings
    .merge(config::File::with_name("config/default.json5"))
    .unwrap()
    .merge(config::Environment::with_prefix("APP"))
    .unwrap();
```

Finally,  here's a `JSON5` config file example (default.json5):
```json5
{
  dbase: {
    connection: {
      connection_string: "mongodb://localhost:27017",
      // connection_string: "mongodb://localhost:27000",
      db_name: "pantobot3d-server",
    },
  },
  mqtt: {
    url: "mqtt://localhost:1883",
  },
}

```

The same error is raised with a `JSON` formatted file with a `json5` extension (default.json5):
```json
{
  "dbase": {
    "connection_string": "mongodb://10.55.0.13:27017",
    "db_name": "pantobot3d-server"
  },
  "mqtt_url": "mqtt://localhost:1883"
}

```

Thanks in advance

**Comment by matthiasbeyer** [comment]
It is definitively in the 0.12 release, but when that lands... I don't know. I'd rather publish it sooner than later, but I cannot promise anything.
