### ISSUE TITLE
Usage of refresh with custom config structs?

### ISSUE THREAD

**Issue by Blakeinstein** [mehcode/config-rs#244]
I am using config-rs in a tauri app. I on start of execution read the config for some default values, that don't necessarily require any kind of refreshing.

As such I have the config go to a global OnceCell. Now, I have some settings that I want to be able to refresh new values when my app is refreshed. As such, I want to be able to update my global config inside my once cell with the original sources.

I see that this exists, but I am unsure how to use this with my own structs, As `Config::refresh` accepts a mutable reference of type config::Config. An example would be great.

**Comment by conradludgate** [comment]
You'd have to wrap the `Config` in a `Mutex` inside of the `OnceCell`, that way you get mutability over the inner config. Otherwise there would be no way to refresh the contents safely

**Comment by matthiasbeyer** [comment]
Yes, exactly. Also having a global variable is .. not optimal, AFAICT. Passing the config object through the application is better I think. And then a `Rc<Mutex<Config>>` or a `Arc<RwLock<Config>>` for a multi-threaded application seems like the better approach!

**Comment by Blakeinstein** [comment]
> Yes, exactly. Also having a global variable is .. not optimal, AFAICT. Passing the config object through the application is better

Which I am aware of yes. But that doesn't really work in an event-based callback system, as used in apps built with [tauri](tauri.studio). Which exposes a webview that can invoke functions written in rust. If you are aware of Electron, then tauri is the same except it takes the place of node.

I see that a `Mutex` is the only option for now, but had hoped an inbuilt refresh method existed.

**Comment by conradludgate** [comment]
If it did, it would be doing the exact same behind the scenes as a mutex

**Comment by matthiasbeyer** [comment]
Wow, I didn't know that tauri got so advanced. Maybe I will try to build a GUI application myself soon! :smile: 

So from what I see there's a guide on [how to manage state with tauri](https://tauri.studio/en/docs/usage/guides/command/#accessing-managed-state) which should be your best bet... With a bit of mutex goodness added, that should get you somewhere!

**Comment by Blakeinstein** [comment]
> So from what I see there's a guide on [how to manage state with tauri](https://tauri.studio/en/docs/usage/guides/command/#accessing-managed-state) 

I dont necessarily need the config to be a state, as I had hoped a full refresh (which would refresh the tauri session) would be able to reload the config. Anyways thanks everyone!
