### ISSUE TITLE
load defaults text - enhancement request

### ISSUE THREAD

**Issue by sagiegurari** [mehcode/config-rs#27]
maybe instead of settings programmatic defaults one by one, I can provide the whole config string as is to be loaded?
this way I can have a file structure as string embedded in the app/library and loaded and on top load an external file which is already supported.
loading a string structure instead of doing it one by one can really help readability of the config and its must easier to code.

**Comment by mehcode** [comment]
That is supported right now actually. Just merge a file (intended for defaults) first so it has lowest priority.

```
config::merge(File::from_str(" ... ", FileFormat::Toml));
```

**Comment by sagiegurari** [comment]
Ah, missed the file.from_str.
That's exactly what I was looking for.
Thanks 👍
