### ISSUE TITLE
Release v0.12.0

### ISSUE THREAD

**Issue by matthiasbeyer** [mehcode/config-rs#278]
I have been thinking about releasing a v0.12.0 a few times already, but I guess we should tackle it.

There [is a milestone](https://github.com/mehcode/config-rs/milestone/2) of a few things I wanted to have in the release, but given that we already have a lot of changes, I would be okay with moving them to the v0.13.0 release.

What do you think, especially @szarykott and @danieleades ? Lets discuss!

---

Also, I need to double-check whether I can make releases on crates.io ! :laughing:

**Comment by danieleades** [comment]
I don't really have a strong preference here. Most of the changes I've made are cosmetic, or at least crate-private.

are all of the issues in the linked milestone still open and relevant?

**Comment by matthiasbeyer** [comment]
Yep, I consider all of them still relevant.

**Comment by danieleades** [comment]
i've been playing around with a strongly-typed, derive-based approach to layered config that sidesteps both issues remaining in that milestone.

it's only a very rough prototype, but potentially of some interest - https://github.com/danieleades/config2/blob/main/tests/default.rs

**Comment by thsioutas** [comment]
Hello! Is there any chance that v0.12.0 is tested with rustc 1.57? There is currently an issue in v0.11.0 and rustc 1.57 (related to lexical-core). Thank you in advance!

**Comment by arbfay** [comment]
Hi all. Just noting that the `examples` folder (the main source of usage docs) now displays an API not working/available in the currently latest released version (0.11). Perhaps a release, or an additional link in the README that points out to a previous commit of master? For the new users 😸 
Keep up the good work though!

**Comment by ximengyi** [comment]
i'm a new user i found examples folder cant‘work.  can anybody tell me what version should i use  if i want  example folder it works

**Comment by matthiasbeyer** [comment]
So it seems that the difference between 0.11 and master really starts to confuse people. I will thus release config 0.12.0 shortly, maybe even today!

@ximengyi You have to make sure that the version of config you use in your code and the documentation/examples you're looking at are the same version! I think you're using `0.11.0` in your code but try to run code that is equal to our example code in master... which won't work as master has features that are not in `0.11.0`.

**Comment by ximengyi** [comment]
> So it seems that the difference between 0.11 and master really starts to confuse people. I will thus release config 0.12.0 shortly, maybe even today!
> 
> @ximengyi You have to make sure that the version of config you use in your code and the documentation/examples you're looking at are the same version! I think you're using `0.11.0` in your code but try to run code that is equal to our example code in master... which won't work as master has features that are not in `0.11.0`.

thanks for your help , I had checkout code from master to  0.11  and the examples code works , i love u

**Comment by matthiasbeyer** [comment]
I just released "0.12.0"! Happy configuring you all! :tada:
