### ISSUE TITLE
Config::builder() not found

### ISSUE THREAD

**Issue by bbeaupain** [mehcode/config-rs#285]
To the authors, thanks for this library! Looking for a quick pointer on getting started if someone has a moment. I'm following the docs in the README on the `master` branch (I've added the `toml` feature myself):

Cargo.toml
```toml
config = { version = "0.11", features = ["toml"] }
```

Following the simple example on the `master` branch:

main.rs
```rust
let settings = Config::builder()
    .add_source(config::File::with_name("examples/simple/Settings"))
    .add_source(config::Environment::with_prefix("APP"))
    .build()
    .unwrap();
```

Compilation gives the following error:

```console
error[E0599]: no function or associated item named `builder` found for struct `Config` in the current scope
  --> src\main.rs:11:28
   |
11 |     let settings = Config::builder()
   |                            ^^^^^^^ function or associated item not found in `Config`
```

How should the builder API be used for simple configuration?

**Comment by matthiasbeyer** [comment]
The version on master branch is newer than the `0.11` release you`re using.
The builder API was added after the `0.11` release.

**Comment by rawkode** [comment]
If you want to use the `Config::builder` API, you need this in your `Cargo.toml`

```toml
config = { git = "https://github.com/mehcode/config-rs", branch = "master" }
```

**Comment by matthiasbeyer** [comment]
(or to have more reproducible builds, a specific commit instead of `master` :laughing: )

**Comment by bbeaupain** [comment]
Thanks all, sorry to take your time for such a simple issue, I was moving a million miles an hour building out a backend and should've stopped to look a little more closely. :)
