### ISSUE TITLE
How to set non required async source ?

### ISSUE THREAD

**Issue by jaudiger** [mehcode/config-rs#293]
Is it possible to set an async source with required to `false` as it's currently possible with `File::with_name("path").required(false)" ?

I didn't find any option when implementing the `AsyncSource` trait. But maybe I'm missed something.

**Comment by Xuanwo** [comment]
It's an implementation detail instead of abstraction at the trait level.

To implement the same thing like `File::with_name("path").required(false)`, just return `Ok(Map::new())` while meeting error if `required=false`.

**Comment by jaudiger** [comment]
Thanks @Xuanwo, got it. i'll close this issue, then.

/close
