### ISSUE TITLE
Support recursively loading from directories

### ISSUE THREAD

**Issue by quodlibetor** [mehcode/config-rs#3]
This is particularly nice for production systems that have potentially large number of config files (e.g. nginx, apache). I think that [the sensu docs](https://sensuapp.org/docs/0.27/reference/configuration.html#configuration-merging) in particular describe the behavior and motivation pretty well.

**Comment by mehcode** [comment]
Here's what I understand about what we want here:
 - Select N files using a glob syntax `conf/**/*.conf`
 - Merge files together in lexical order `00-file.conf` is added before `01-file.conf`

Does it make sense to add this "glob" API to the existing `config::File` source API? Or, should it be its own API?

```rust
config::merge(config::File::from_glob("conf/**/*.conf"));

// or

// Not a fan of 'config::FileGlob' but I'm sure we could think of a better name
config::merge(config::FileGlob::new("conf/**/*.conf"));
```

**Comment by mehcode** [comment]
Decided to go with

```rust
config::File::with_pattern("conf/**/*.toml")
```

**Comment by quodlibetor** [comment]
Is that a helper that delegates internally to a merge function? That API seems pleasant, and exposing something that accepts an iterable of (already ordered) `Path`s would also be nice.

**Comment by mehcode** [comment]
I was going to make this an _optional_ feature and delegate to https://doc.rust-lang.org/glob/glob/fn.glob.html

---

What you're talking about actually makes a lot of sense. I didn't think of it before but we could easily just `impl From<Path> for File`

```rust
config::File::from(Path::new("/tmp/foo/bar.json"));
config::File::from(vec![Path::new("/tmp/foo/bar.json"), Path::new("/tmp/a/foo.toml")]);
config::File::from(Path::new("/tmp/foo/bar.conf")).format(config::FileType::Json);
```

**Comment by quodlibetor** [comment]
Yup, `with_pattern(&str)` is the more ergonomic option, but implementing for `Path` and `&IntoIterator<Item=Path>` is more flexible.

**Comment by mehcode** [comment]
Decided to _just_ do the from path approach. 

https://github.com/mehcode/config-rs/blob/master/examples/pattern/src/main.rs#L40-L45

I feel that's ergonomic enough for this use case and is far more flexible in the long run.
