### ISSUE TITLE
Add set_override_optional combinator to ConfigBuilder

### ISSUE THREAD

**Issue by saraiva132** [mehcode/config-rs#302]
Hey :)

Using ConfigBuilder and in case I have overrides that are optional, i.e. env_vars which may not be there, it would be quite idiomatic to add this combinator to avoid having:

` if let Ok(my_var) = b.set_override("region", region)?;`

In my case I would just convert my `Result` to `Option`

```
Config::builder()
            //Merge default config folder
            .add_source(default_config_file)
            .set_override_optional(my_optional_field)
```

I can submit a PR for this if you like :) Perhaps also for `default_optional`

WDYT?

**Comment by matthiasbeyer** [comment]
Hey! Thanks for opening this issue. I am not sure what the actual implications of having an optional overwrite would be? Either you overwrite a value, or you don't. What would an optional overwrite actually be?

**Comment by saraiva132** [comment]
@matthiasbeyer If optional value exists override otherwise do nothing.

**Comment by matthiasbeyer** [comment]
And where would such an optional value come from? Do you have an example? :thinking:

**Comment by saraiva132** [comment]
My use case is as mentioned.

```
let a = env::var("MY_INJECTED_VAR_A").ok();
let b = env::var("MY_INJECTED_VAR_B").ok();
let c = env::var("MY_INJECTED_VAR_C").ok();
Config::builder()
            //Merge default config folder
            .add_source(default_source)
            .set_override_optional("a", a)?
            .set_override_optional("b", b)?
            .set_override_optional("c", c)?;
```

Avoids this ugly syntax

```
        let builder = match env::var("MY_INJECTED_VAR_A") {
            Ok(a) => builder.set_override("a", a)?,
            Err(_) => builder,
        }
```

Perhaps this use case is not enough. I admit I am not able to discern others.

**Comment by matthiasbeyer** [comment]
Why would you not [read environment variables](https://docs.rs/config/latest/config/struct.Environment.html) via `config`?

**Comment by saraiva132** [comment]
I also read them via `config` but unfortunately a couple of them do not follow any pattern and must be individually loaded. `Environment` in config is not "powerful" enough for that

**Comment by zhrebicek** [comment]
I guess it makes sense to have something like this.
Good example is some multi language environment having lot of shared environment variables where you do not want to add arbitrary prefix like `APP_` but also do not want to load them all blindly.

**Comment by matthiasbeyer** [comment]
Hm. I think I would like to see a PR for this, yes.
