### ISSUE TITLE
proposal: Introduce temp-env for better env test

### ISSUE THREAD

**Issue by Xuanwo** [mehcode/config-rs#314]
Hi, I saw our unit tests failed randomly like:

- https://github.com/mehcode/config-rs/runs/5805369539?check_suite_focus=true
- https://github.com/mehcode/config-rs/runs/6010922223?check_suite_focus=true

How about introduce [temp-env](https://github.com/vmx/temp-env) for better env test?

```rust
temp_env::with_vars(
    vec![
        ("FIRST_VAR", Some("Hello")),
        ("SECOND_VAR", Some("World!")),
    ],
    || {
        // Run some code where `FIRST_VAR` is set to `"Hello"` and `SECOND_VAR` is set to
        // `"World!"`.
    }
);
```

If it looks good to you, I'm willing to start a PR for it. :laughing:

**Comment by matthiasbeyer** [comment]
I didn't know about the temp-env crate. Sounds good, I'd love to see a PR for that! :+1:
