### ISSUE TITLE
proposal: Implement serde::Serializer and Source/AsyncSource for Value

### ISSUE THREAD

**Issue by Xuanwo** [mehcode/config-rs#315]
I'm working on an app that uses `clap` for command line args parsing. I want to support loading configs in various ways with the specific rules:

- loading from env
- loading from config files
- loading from args

To avoid duplicate code, I'm trying to use:

```rust
struct App {
  #[clap(flatten)]
  config: Config,
}

struct Config {
   ...
}
```

To make our config values merge correctly, we should take values that parsed via `clap` as a source:

```rust
let mut builder = Config::builder()
    .add_source(Environment::default())
    .add_source(File::new("config/settings", FileFormat::Json))
    .add_source(Config::parse());
```

In order to make that code works, we need:

- Implement `serde::Serializer` for `Value`, so we can build `Value` from the config struct itself. (Maybe implementing `Into<Value>` is enough?)
- Implement `Source`/`AsyncSourc` for `Value`, so we can use the value as a source (it's trivial and makes sense, right?)

What do you think about this idea?

**Comment by matthiasbeyer** [comment]
I am not 100% sure whether this could or even should be done, but I wouldn't mind to see a PR for this.

Please make sure to feature-gate it, so that users of `config` who don't want to use `clap` don't have to pull it in! :smile:

**Comment by Xuanwo** [comment]
> I am not 100% sure whether this could or even should be done, but I wouldn't mind to see a PR for this.

Sadly, I failed to implement this without a huge refactor on `Value`. :cry: 

Let's close this issue.
