### ISSUE TITLE
Merging an invalid but existing and non-required file should return an error

### ISSUE THREAD

**Issue by Anthony25** [mehcode/config-rs#32]
Hello,
When merging a non-required file, in my opinion an error should be triggered if the file exists but cannot be parsed (invalid syntax in yaml, for example).
Currently, the result is Ok(), even if the parsing has failed.

What is your opinion about this behavior?
Thanks!

**Comment by mehcode** [comment]
@Anthony25 I'd call this a bug. 

https://github.com/mehcode/config-rs/blob/master/src/file/mod.rs#L98-L103

If you want to submit a PR to fix that I'll merge it. Otherwise,  I'll get to it when I find time for v0.6.

**Comment by Anthony25** [comment]
Thanks,
Sure, will do.
