### ISSUE TITLE
Can't override nested settings

### ISSUE THREAD

**Issue by sedrik** [mehcode/config-rs#333]
Given a Config structure like

```rust
#[derive(serde::Deserialize, Debug)]
pub struct Settings {
    pub authentication_url: String,
    pub database: DatabaseSettings,
}

#[derive(serde::Deserialize, Debug)]
pub struct DatabaseSettings {
    pub host: String,
}
```

And the following config setup

```rust
    let config = Config::builder()
        .add_source(config::File::from(
            configuration_directory.join("base.yaml"),
        ))
        .add_source(config::Environment::with_prefix("APP"));
```

I am able to use `APP_AUTHENTICATION_URL` to override settings.authentication_url but when I try `APP_DATABASE_HOST` my customization is not detected. Is there something special I need to do to allow env overrides for nested configs?

Using the following entry in Cargo.toml
```rust
config = "0.13.0"
```

**Comment by szarykott** [comment]
It is more of an educated guess and quick look at env.rs, but did you try something like `APP_DATABASE.HOST`?

**Comment by kjaleshire** [comment]
It's non-obvious but you must explicitly set the separator, otherwise the environment source won't attempt to break up the key into nested components:
```rust

std::env::set_var("APP_DATABASE_HOST", "postgres://foo.url");

let config = Config::builder()
    .add_source(config::File::from(
        configuration_directory.join("base.yaml"),
    ))
    .add_source(config::Environment::with_prefix("APP").separator("_"))
    .try_deserialize()
    .unwrap();

println!("{}", config.database.host);
// # postgres://foo.url
```

**Comment by kjaleshire** [comment]
@szarykott or @mehcode , is there a reason nesting is impossible using env vars by default?

**Comment by matthiasbeyer** [comment]
It seems to me that the env-var stuff makes more problems than it solves. :cry:

**Comment by sedrik** [comment]
Ah, setting the separator did indeed solve it.

While the env overwrite logic complicates things it is really nice for running the same docker in different envs.

Thanks for the support, it's a great library to use :heart:

**Comment by mawkler** [comment]
To anyone that, like me, has trouble using nested field names with underscores in them like `database.host_url`, I tried a bunch of other separators like `.` and `-` but they don't seem to be allowed. My solution was to use double underscores as separator `__`:

`.add_source(config::Environment::with_prefix("APP").separator("__"))`
