### ISSUE TITLE
Add `.recursive` on config::File

### ISSUE THREAD

**Issue by mehcode** [mehcode/config-rs#35]
Allow to control upwards recursion when searching for configuration files.  The only real question is if the upwards recursion should be default true or false.

```rust
// ./config/default.toml OR ../config/default.toml 
// OR ../../config/default.toml (etc., whatever ends up matching)
File::with_name("config/default.toml").recursive(true)
```

**Comment by tmccombs** [comment]
To me, I would expect "recursive" to search down the file hierarchy recursively not up. That name seems odd to me.

**Comment by mehcode** [comment]
I agree. I can't think of a good name unless I make it super long. Ideas are welcome.

**Comment by tmccombs** [comment]
`search_parents`?

**Comment by mehcode** [comment]
Hmm. I could just leave this out and tell people to use something like the findup crate.

```rust
extern crate config;
extern crate findup;

fn main() {
  let settings = config::Config::default()
    .merge(config::File::from(findup::findup("config/default.toml"))
    .unwrap();
}
```

**Comment by mehcode** [comment]
Closing because the above solution is simple enough if that's what you want.
