### ISSUE TITLE
Set default value for subconfig

### ISSUE THREAD

**Issue by jgirardet** [mehcode/config-rs#351]
Hi people,
say you have:
```rust
#[derive(serde::Deserialize, Debug)]
pub struct Configuration {
 a: AConfiguration
}
#[derive(serde::Deserialize, Debug)]
pub struct AConfiguration {
some: String
}
```
How do you call Builder.set_default() to pass a value to `a_some` ?

```rust
set_default("a_some", "bla".to_string())
or
set_default("a", A{some:"bla".to_string())
```
don't work

Thanks for help
Jimmy

Edit: seems to work, passing a config::Map as default value.

**Comment by matthiasbeyer** [comment]
> Edit: seems to work, passing a config::Map as default value.

Does this mean your issue is resolved? :laughing:

**Comment by matthiasbeyer** [comment]
If it works for you, then it is the way to do it right now, yes.
I hope, though, that we can improve the situation at some point to make these things less complex on the users side. :laughing:
