### ISSUE TITLE
Spurious error message for duplicate key with mixed TOML syntax for map

### ISSUE THREAD

**Issue by newca12** [mehcode/config-rs#368]
Both TOML syntax for maps are well handled by config but there is an inconsistency regarding error message.

This give a spurious error message
`Err` value: invalid type: sequence, expected a string for key `items[0]items`
````
[[items]]
name = "john"

items = [{ name = "joe"}]
````

Inverting the order give attented error message
`Err` value: duplicate key: `items` at line 3 column 1 in Settings.toml'
````
items = [{ name = "joe"}]

[[items]]
name = "john"
````

**Comment by matthiasbeyer** [comment]
Can you share the code you're deserializing to?

**Comment by newca12** [comment]
````rust
use config::{Config, ConfigError, File, Map};
use serde_derive::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Settings {
    pub items: Vec<Map<String, String>>,
}

impl Settings {
    pub fn new(file_settings_path: &str) -> Result<Self, ConfigError> {
        let settings = Config::builder()
            .add_source(File::with_name(
                format!("{}Settings.toml", file_settings_path).as_str(),
            ))
            .build()?;
        settings.try_deserialize()
    }
}

````

**Comment by matthiasbeyer** [comment]
So the first toml example you gave would deserialize into something like this:

```rust
struct Item {
    name: String,
    item: SubItem,
}
struct SubItem {
    name: String,
}
```

The second example you gave is not valid TOML (`toml::from_str` fails on it).

**Comment by newca12** [comment]
Oh I see thanks, I didn't see that it was only a toml crate error string and nothing to do with the config crate itself.
FWIW the explanation for what can be seen a bit confusing at first glance.
```toml
items = [{ name = "joe"}]
```
is [often](https://stackoverflow.com/a/41326744) see as a short TOML syntax for
```toml
[[items]]
name = "joe"
```
but **as you point out** it is not, This can be illustrated with these examples
This is not a valid TOML (duplicate key)
````toml
items = [{ name = "joe"}]
items = [{ name = "joe"}]
````
This is valid TOML (no duplicate key)
````toml
[[items]]
name = "john"
[[items]]
name = "john"
````
