### ISSUE TITLE
File Format `k=v` support

### ISSUE THREAD

**Issue by hal8888** [mehcode/config-rs#383]
Hi, I need this kind of config format loaded from file:
```
CONFIG1=value
CONFIG2=123
```
When I tried with `ini` feature, it produces panic.
Please support this kind of format in file, Thanks!

**Comment by jpmckinney** [comment]
I am using ini just fine – need to share example code to reproduce and diagnose.

**Comment by polarathene** [comment]
Closing as reporter did not respond, feature should work with INI format already.
