### ISSUE TITLE
Error on calling method "origin" on type Value

### ISSUE THREAD

**Issue by hkr1990** [mehcode/config-rs#385]
I'm trying to call this public function "origin" on a Value type and I'm getting this error "^^^^^ private field, not a method". Also, the method is public in the code but not in the API documentation.

Defined in value.rs
    /// Get the description of the original location of the value.
    pub fn origin(&self) -> Option<&str> {
        self.origin.as_ref().map(AsRef::as_ref)
    }

**Comment by matthiasbeyer** [comment]
The commit that added the `Value::origin()` method is not yet released on crates.io!
