### ISSUE TITLE
Conflict with serde_yaml

### ISSUE THREAD

**Issue by sapsan4eg** [mehcode/config-rs#39]
Hi, i have issue with using together serde_yaml and config. When I compile an application, I get an error
```
 0 => yaml::Yaml::Hash(BTreeMap::new()),
   |                               ^^^^^^^^^^^^^^^ expected struct `linked_hash_map::LinkedHashMap`, found struct `std::collections::BTreeMap`
```
The reason is that the serde_yaml uses the feature \"linked-hash-map\" of yaml-rust. This feature indicates that type yaml::Hash is equivalent to ::linked_hash_map::LinkedHashMap<Yaml, Yaml>; 
https://github.com/chyh1990/yaml-rust/blob/0.3.5/src/yaml.rs#L65

You can reproduce this issue. Just add to Cargo.toml in another project this two crates. And try to compile.

**Comment by mehcode** [comment]
@sapsan4eg Thanks for reporting. This should be fixed with https://github.com/mehcode/config-rs/commit/71f4b182d1e56febda64bd620ae0e0f65de333cd. Can you try using master and see if your problem is resolved?

```toml
[dependencies]
config = { git = "https://github.com/mehcode/config-rs"  } 
```

**Comment by sapsan4eg** [comment]
Yes, it works. Thank you. When is the release expected?

**Comment by mehcode** [comment]
@sapsan4eg I have tomorrow planned to clean up a few more issues and push a release. I want to take another crack at properly fixing #36 (but still supporting the chain API) before releasing.
