### ISSUE TITLE
Question: Is there a way to embed config files?

### ISSUE THREAD

**Issue by bryantbiggs** [mehcode/config-rs#408]
If I am distributing a CLI, the executable currently fails because the config files do not travel with the binary. I don't know if I am missing something obvious but is there a way to embed the configuration files referenced? Something like

```rs
use config::{Config, ConfigError, File};
use rust_embed::RustEmbed;

#[derive(RustEmbed)]
#[folder = "assets/"]
struct Asset;

let s = Config::builder().add_source(File::with_name("assets/config.yaml")).build()?;
s.try_deserialize()
```

**Comment by matthiasbeyer** [comment]
You're already using `rust_embed` up there, that already embeds the file in your binary. You just have to use it from there!
