### ISSUE TITLE
Towards 1.0

### ISSUE THREAD

**Issue by mehcode** [mehcode/config-rs#41]
- [ ] API Documentation

 - [ ] Clean up implementation and ensure all public methods have several unit tests (where possible). Sources should have integration tests. Look into code coverage.

 - [ ] Clean up implementation warts. There is a few areas of duplicated impls. Mostly in the config deserializer.

 - [ ] Change `config::Environment` to only collect env vars for keys that are already present in the config instance. 

 - [ ] Allow selecting which environment variables to consume
   ```rust
   Environment::new().keys(&["debug"])
   ```

 - [ ] Consider deferring configuration loading until the first access. Would require interior mutability, however, the [docs](https://doc.rust-lang.org/std/cell/index.html#implementation-details-of-logically-immutable-methods) indicate that "caching" is an accepted usage of interior mutability and that's essentially what the configuration loading is doing.

 - [ ] Make `Config#merge` API more ergonomic for simple use cases.
    ```rust
    config.merge("Settings.toml");  // &str impls Into<Path> which impls Into<config::File>
    ```

 - [ ] Round out format support: [xml](https://github.com/RReverser/serde-xml-rs), [hjson](https://github.com/hjson/hjson-rust), [libconfig](https://github.com/mehcode/config-rs/issues/15), [.env](https://github.com/mehcode/config-rs/issues/16)

 - [ ] Remote support: [etcd](https://github.com/mehcode/config-rs/issues/11) and [consul](https://github.com/mehcode/config-rs/issues/12)

 - [ ] Rename `Config#refresh` to `Config#reload`

 - [ ] https://github.com/mehcode/config-rs/issues/19

---

If you have any pain points when using Config or you'd like to share how you use Config, today, please comment below.

**Comment by svenstaro** [comment]
Why close this?

**Comment by mehcode** [comment]
@svenstaro The list has atrophied enough that it needs to be rethought. I definitely still want feedback on pain points or possible improvements in issues though.
