### ISSUE TITLE
Option<Decimal> always None

### ISSUE THREAD

**Issue by telcy** [mehcode/config-rs#414]
config.yml
```
foo: 100.0
bar: 200.0
```

```
use rust_decimal::Decimal;
use serde::Deserialize;

#[derive(Debug, Deserialize)]
pub struct Config {
    pub foo: Decimal,
    pub bar: Option<Decimal>,
}
```

bar should be Some(200.0) but is always None.

**Comment by matthiasbeyer** [comment]
Hi! Thanks for your report. Unfortunately I cannot reproduce, see #415

**Comment by telcy** [comment]
Thank you. Appreciate your help.
It is all working as intended and it turns out my slightly more complex case had a bug.

Keep up the good work.
