### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by a-dma** [mehcode/config-rs#42]
It would be useful to have the possibility to specify data ranges or callbacks to validate data read from a configuration file and returning a dedicated error if no match is found.

Is this something you'd be willing to incorporate?

**Comment by mehcode** [comment]
Could you elaborate on how you use config-rs today? Do you read files and access values using JSONPath? Or, do you deserialize the configuration into a structure?

If the latter, I'd recommend you use https://github.com/Keats/validator. We could even make the `.validate` call inside of config-rs with a feature flag or something.

**Comment by a-dma** [comment]
I deserialize them into a struct.
Thanks for the link, I didn't know of that crate. I assume this would be a fairly common use-case. Maybe it's worth having a couple of lines about it in the README or in an example?

What I've been doing so far is manually checking ranges for strings and numeral types, and I wrote my own deserializer for enums. That of course includes some sort of validation.

**Comment by mehcode** [comment]
Closing because the answer is to use the linked validator lib. Config is about getting your configuration into your struct, not that the values match a schema.
