### ISSUE TITLE
Environment struct not loading .env file

### ISSUE THREAD

**Issue by dev-davexoyinbo** [mehcode/config-rs#448]
Using the Environment struct doesn't load environment variables in .env file

```rust
let mut environment_data: HashMap<String, String> = Config::builder()
            .add_source(Environment::default())
            .build()?.try_deserialize()?;
log::error!("Environment Data: {:?}", environment_data);
```

Or is there a way to only load the .env file?

**Comment by matthiasbeyer** [comment]
This crate does not feature functionality to load `.env` files, just as it does not feature functionality to interpolate environment variables (which I answered in https://github.com/mehcode/config-rs/issues/447#issuecomment-1666865128 already).

**Comment by dev-davexoyinbo** [comment]
Yes, thank you. I used handlebars and it now works

https://github.com/mehcode/config-rs/issues/447#issuecomment-1666885398
