### ISSUE TITLE
Add more usage examples to hierarchical-env

### ISSUE THREAD

**Issue by SkeLLLa** [mehcode/config-rs#45]
Hello. I'm quiet new to rust, so it will be good for me if you add some advanced examples of usage, especially to hierarchical-env example.

What's the best or correct way of accessing nested config values in `main.rs`, like it's done here: https://github.com/mehcode/config-rs/blob/f70a2d406387fb338f842ba22924d3076da97e22/examples/hierarchical-env/src/main.rs#L15
but to get only value of `debug` config variable, whole `twitter` or just only `consumer_token`

**Comment by mehcode** [comment]
Hey @SkeLLLa. I agree the examples could be made a bit more friendly. 

You can use a restricted form of JSONPath that only allows direct traversal:

```rust
let mut settings = Config::new();

// [...] Configure settings [...]

// Access "debug"
println!("{:?}", settings.get::<bool>("debug"));
println!("{:?}", settings.get_bool("debug"));

// Access the twitter object as a hash map
// Planning to export `config::Table` so this is easier to write if wanted
println!("{:?}", settings.get::<HashMap<String, config::Value>>("debug"));
println!("{:?}", settings.get_table("debug"));

// Access a nested property in the twitter object
println!("{:?}", settings.get::<String>("twitter.consumer_token"));
println!("{:?}", settings.get_str("twitter.consumer_token"));
```

---

We should probably separate the hierarchical env example from an example that looks at struct deserialization. I'd guess most people coming from other languages that have a "hierarchical env" type thing are more used to just getting properties directly.

**Comment by SkeLLLa** [comment]
@mehcode thanks for examples, but I've asked about a little bit different thing. In that example there is
```
let settings = Settings::new();
```
https://github.com/mehcode/config-rs/blob/f70a2d406387fb338f842ba22924d3076da97e22/examples/hierarchical-env/src/main.rs#L12

instead of 
```
let mut settings = Config::new();
```
like in your example.

Thus it has no `.get` method. And that's basically what I'm asking about.

**Comment by SkeLLLa** [comment]
The most sane way I've found is to make everything in settings public:
settings.rs
```
#[derive(Debug, Deserialize)]
pub struct Consul {
    pub host: String,
}

#[derive(Debug, Deserialize)]
pub struct Settings {
    pub debug: bool,
    pub consul: Consul,
}

impl Settings {
    pub fn new() -> Result<Self, ConfigError> {
        let mut s = Config::new();
        s.merge(File::with_name("config/default"))?;
        let env = env::var("RUN_MODE").unwrap_or("development".into());
        s.merge(File::with_name(&format!("config/{}", env)).required(false))?;
        s.merge(File::with_name("config/local").required(false))?;
        s.merge(Environment::with_prefix("app"))?;
        s.try_into()
    }
}
```

and unwrap settings in  main.rs and use them:
```
fn main() {
    let settings = settings::Settings::new();
    println!("{:?}", settings.unwrap().consul.host);
}
```

Is it ok? Or may be there is better way to do this?

**Comment by mehcode** [comment]
Public fields are more than acceptable.
