### ISSUE TITLE
Fail if an unrecognized knob is detected

### ISSUE THREAD

**Issue by QnJ1c2kNCg** [mehcode/config-rs#450]
Is this something like a _strict_ mode, where during the configuration parsing, if a configuration knob is not recognized, the entire `Config` creation fails?

Thanks!

**Comment by matthiasbeyer** [comment]
I believe that you can annotate your structs with [`deny_unknown_fields`](https://serde.rs/container-attrs.html#deny_unknown_fields) and when you deserialize to your own types, deserialization should fail if a field is encountered that you didn't expect.

Does this work for you?

**Comment by QnJ1c2kNCg** [comment]
this is what i needed, thanks!
