### ISSUE TITLE
Picking up values from environment not working

### ISSUE THREAD

**Issue by algermissen** [mehcode/config-rs#47]
Hi,

I am trying to use the environment only, to grep the configuration. Because that did not work, I also tried with an additional Settings.toml. Then the value from file is picked up, but not the environment.

Code:

    let mut settings = config::Config::default();
    settings
       .merge(config::File::with_name("Settings"))
        .unwrap()
        .merge(config::Environment::with_prefix("APP"))
        .unwrap();

    let x = settings.get::<String>("foo").expect("ok");
    println!("CFG: {:?}", x);

Settings.toml:
`foo = "20"`

Calling the program with `APP_FOO=10 target/debug/prog`. Only the value from toml is picked up.

I must be doing something very stupid, but I cannot get this to work. Can you spot my error?

**UPDATE** Also tried the simple example, with APP_DEBUG=FOO without success. The toml file wins.

The crazy thing is that to me the code in Environment looks fine, I am just not getting what is going on.

**UPDATE**
See new comment https://github.com/mehcode/config-rs/issues/47#issuecomment-339638438 below.

**Comment by algermissen** [comment]
It works with the latest version, which I did not quite have - I had 0,.6 from the github README.

**Comment by algermissen** [comment]
I found one more issue with reading the environment. The separator (default '_') is not split once, but several times. For example, if you have APP_CACHE_SIZE in the environment, you do not get a config var "cache_size", but two vars, 'cache' and 'size' (I guess in a hierarchy, but I did not check that).

I found this counter-intuitive when working with env vars.

If this is not a bug, but intended behaviour, a special note in the docs would help avoid this interpretation.

**Comment by mehcode** [comment]
It was intended. A key like `APP_CACHE_SIZE` would become `cache.size`. The idea was to override structured configuration you might have.

I don't want to remove this entirely (as done in #56) but I'd be okay with disabling it by default and having perhaps:

```rust
Environment::with_prefix("APP").separator("_")
```
