### ISSUE TITLE
Reset to default values

### ISSUE THREAD

**Issue by vessd** [mehcode/config-rs#48]
I want to handle multiple configurations with the same fields.
I have the default settings and N configuration files. I want to merge the default settings with each file separately and as a result, get N structures with the settings.
How to reset values or parse them using only one source?
```rust
let mut config = Config::new();
config
    .set_default("host", "localhost")?
    .set_default("port", 21)?
    .set_default("user_id", 0)?;
config.merge(File::with_name("foo"))?;
let host_foo: Host = config.try_into()?;
config.reset(); // <-- reset to default
config.merge(File::with_name("bar"))?; // merge only with default values
let host_bar: Host = config.try_into()?;
```

**Comment by mehcode** [comment]
You can do `config2.merge(config1)`. That would let you keep config1 from mutating.
