### ISSUE TITLE
New release/sync from master

### ISSUE THREAD

**Issue by bbaldino** [mehcode/config-rs#509]
Yesterday I ran into an issue where environment variable overrides weren't working correctly and I realized it's because of [this line](https://github.com/mehcode/config-rs/blob/a38387955622e6b8d48a49352629cd329ad6dc29/src/de.rs#L249) which does a case-sensitive comparison when looking for a variant constructor, but even changing the capitalization of the environment variable doesn't fix it because they get lower-cased in `env.rs`.  I notice that [master has a fix for this to be case insensitive](https://github.com/mehcode/config-rs/blame/4457cffb681e9765e364afb24cd28e247f9dc6e5/src/de.rs#L275) but it looks like the `release-0.13.x` branch peeled off from master a long time ago (the change was made in master 2 years ago).  Are there plans to sync with master and bring in this fix before doing another release?

**Comment by polarathene** [comment]
I think maintenance is rather low for `config-rs` lately.

- I have some PRs that I still need to wrap up myself (_and hoping to finally have time for this month_).
- I don't have the time to commit as a maintainer of the project myself, and it doesn't seem like there is anyone else coming forward to actively maintain the project.
- You'll possibly have to submit a PR with any changes you want into master. I imagine a new release will happen after my PRs are merged.

Alternatively, you may want to look into other crates with similar functionality that are more active in development / maintenance? (_unless I'm mistaken with the current state of maintenance_).

**Comment by bbaldino** [comment]
Thanks for the response.  The fix I'm looking for _is_ in master, but I guess the PR would be porting it over to the `release-013.x` branch, which I do think would be pretty simple...but I guess the question is if that's worthwhile.  It also makes me wonder what other fixes are in master that haven't been brought over, I suppose.

**Comment by bbaldino** [comment]
Thanks @matthiasbeyer !

**Comment by matthiasbeyer** [comment]
Sure thing!

Just make sure to submit bug reports (or even better: Fixes) for everything you might hit! :heart:
