### ISSUE TITLE
rust-ini version mismatch in github code and crates.io

### ISSUE THREAD

**Issue by mario-nt** [mehcode/config-rs#548]
In the Cargo.toml file the required version for the dependency library **rust-ini** is 0.20.0:

https://github.com/mehcode/config-rs/blob/4896caf29a71174eeb6af884bba84bb99ca9bb87/Cargo.toml#L36

However, in the crates.io page and when downloading the package, the required version is 0.19.0:

![image](https://github.com/mehcode/config-rs/assets/141633147/5e492449-21ab-4160-8cf5-80d6ce2bc53d)

We are getting some workflows errors due to outdated packages that rust-ini v0.19.0 uses (because when using the config-rs version from crates.io, we get the v0.19.0 in the dependency instead of  0.20.0)

**Comment by matthiasbeyer** [comment]
`config 0.14.0` is released with `rust-ini 0.19`. What you see is the unreleased version on the master branch.

Once the next release of the `config` crate happens, the latest `rust-ini` version will be in the dependencies (`0.20` as of now, but `0.21` is already out there, so I guess dependabot will PR the update soon).

**Comment by mario-nt** [comment]
@matthiasbeyer Okay, it makes sense, didn't think about it in that way. 

Thank you so much for answering Matthias :)

**Comment by matthiasbeyer** [comment]
I am gonna close this as it really is not the issue. Feel free to reopen if you like to object! 😄
