### ISSUE TITLE
When no configs are present, Config::new() should default to the structs default

### ISSUE THREAD

**Issue by elliott-davis** [mehcode/config-rs#60]
In an application, sometimes there is no config present and you would just like to use the default values for your struct. If this is the case currently, you get an obtuse error like: `invalid type: unit value, expected struct Settings`. As an example usage:

```
#[derive(Debug, Deserialize)]
pub struct Settings {
    db_host: string,
}

impl Default for Settings {
    fn default() -> Self {
        Settings {
            db_host: IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)),
        }
    }
}

impl Settings {
    pub fn new() -> Result<Self, ConfigError> {
        let mut s = Config::new();
       // hand waiving pseudo code
        if config_file.present() {
           s.merge(File::with_name(config_file))?;
       }
       s.try_into()
}
```

**Comment by Michael-F-Bryan** [comment]
I was looking for this exact feature. Originally I thought you could work around it by converting/serialising your `Settings` into a `Value` and swapping out the `Config`'s `cache` field. But there doesn't seem to be any way to do this...

**Comment by elliott-davis** [comment]
@Michael-F-Bryan that sort of worked. However whenever I merged a file my cache override got blown away. After reading through the config merge code I see that the cache is repopulated from `ConfigKind` on each `refresh`.

**Comment by Michael-F-Bryan** [comment]
I think a better solution would be to have a `with_default()` method which accepts some default object and if it's a map it'll iterate over the items, calling `set_default()` for each.

**Comment by mehcode** [comment]
How about:

```rust
s.set_defaults::<Settings>()?;
```

`Config::set_defaults<T>` accepts a `T` that is `Serialize + Deserialize + Default`. Config could transform a generic `T` that way and set that as default values.

**Comment by vorner** [comment]
I think there are two issues here, aren't there?

First one is how to use defaults ‒ and the answer for that one is to use the serde's default handling (eg. the `default` attribute on fields).

The other problem is the annoying `unit value` error. I managed to work around that one by merging an empty source as the first one, eg `config.merge(File::from_str("", FileFormat::Toml))?`. Could something like this be already done as part of the constructor? I mean, make sure whatever is tried to be deserialized looks like an empty map to serde, not unit.

**Comment by mehcode** [comment]
I didn't see that before. Thanks for making that clear. This is more of a bug then. Marking to get fixed for 0.10.

**Comment by Kirguir** [comment]
Creating a config so
```
let mut s = Config::try_from(&Settings::default())?;
```
expect that the values will fall into `defaults`  and then can overwrite them. 

But `ConfigSerializer` writes in `overrides`
```
self.output.set(&key, value.into())?;
```
:disappointed_relieved:

**Comment by derekdreery** [comment]
This can also be fixed by a call to `config.refresh()`, which avoids an allocation.
