### ISSUE TITLE
Support YAML files with sub parameters

### ISSUE THREAD

**Issue by ritiek** [mehcode/config-rs#61]
I tried parsing some YAML files (using [this example](https://github.com/mehcode/config-rs/tree/master/examples/simple)). However, if YAML happens to contain sub heading/parameter like:

```yaml
sub_heading:
  key: value
```

It errors out with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: invalid type: map, expected a string', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It would be nice to have support for such YAML files.

**Comment by GuilhermeHideki** [comment]
In this case, you would get the value using ``settings.get::<String>("sub_heading.key")``.

The error is because ``settings.try_into::<HashMap<String, String>>`` expects String in value.
Since I'm new in Rust, I don't know how to print all data inside too.

**Comment by mehcode** [comment]
@GuilhermeHideki is correct. That example is perhaps too simple. Sub-maps are supported but not for deserializing to `HashMap<String, String>`.
