### ISSUE TITLE
Fields with camelCase doesn't work

### ISSUE THREAD

**Issue by vjousse** [mehcode/config-rs#65]
Hi there,
I'm new to rust and config-rs, and I'm facing an annoying problem: I can't get structs with `#[serde(rename_all = "camelCase")]` to work.
I've setup a [simple demo repository here](https://github.com/vjousse/test-config-rs) to illustrate my problem.
My Toml:
```toml
snakeTest = "foo"
```
My struct:
```rust
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Settings {
    snake_test: String,
}
```
My main:
```rust
fn main() {
    let mut c = config::Config::default();
    c.merge(config::File::new("Settings", config::FileFormat::Toml))
        .unwrap();

    // Deserialize the entire file as single struct
    let s: Settings = c.try_into::<Settings>().unwrap();

    println!("{:?}", s);
}
```
The error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: missing field `snakeTest`', libcore/result.rs:916:5
```

Am I missing something? Thanks!

**Comment by vjousse** [comment]
This seems to be related to this `to_lowercase` call here: https://github.com/mehcode/config-rs/blob/master/src/file/format/toml.rs#L32

Any reason why your are lowercasing every key?

**Comment by mehcode** [comment]
The primary reason is it's not always straightforward what case the key is in when it comes into the application. Consider building your application targeting a configuration file where all keys are `lower_case` but the system administrator needs to override something with an environment variable as `UPPER_CASE`.

I'd be hesitant to start doing `camelCase` to `camel_case` conversions everywhere. It might make sense to allow uniformly changing keys from a specific source though. Perhaps something like this:

```rust
config.merge(
  File::new("Settings").key_replacer(|key| to_lower_case(key))
)?;
```

**Comment by vjousse** [comment]
IMHO, a first good step would be adding some documentation about that. For example, warning people that keys in the files should be lowercase when using automatic deserialization with `try_into`.
What's your guidelines regarding the main `README.md`? It seems pretty poor atm, and this is very confusing for the newcomers. I may contribute some documentation if you want. Just tell me if I can help in that area.
Anyway, thanks for the answer and the great work!

**Comment by bowbahdoe** [comment]
This is surprising behaviour to say the least. It makes reading in json written in camel case pretty hard and it seems like an unnessicary restriction.

**Comment by mehcode** [comment]
Being fixed for `0.10`. Keys will be case-sensitive on a per-source basis (so keys coming from the environment will still be case-insensitive).

**Comment by ufoscout** [comment]
@mehcode 
Is there any estimated date for 0.10.0 to be released? If not, would it be possible to have a patch for this in 0.9?
We use this library in each of my company's project, but we are forced to migrate to something else as this bug is a huge issue for us :(

**Comment by arsing** [comment]
It is also possible to implement your own `config::Source` that's similar to `config::File` but doesn't lower-case the keys. That's what we do in https://github.com/Azure/iotedge/blob/master/edgelet/edgelet-config/src/yaml_file_source.rs

**Comment by polarathene** [comment]
I just ran into this with my TOML config when following the example to `try_into()` deserialize into structs, where a TOML table(key/value object) was to deserialize into a HashMap field in my struct. I expected the keys to respect case sensitivity of the [TOML spec](https://github.com/toml-lang/toml#spec):

> TOML is case sensitive.

The part of the config that depended on that was a parameter mapping of key/value pairs for the query string of an HTTP request that gets made by my program. I don't control the HTTP API that is being requested and these parameter keys are sometimes dynamic with their names, so it seemed like a good idea to make available to users via config for the combinations they require.

**Comment by mehcode** [comment]
That is more than fair. I've let this languish for a long time. I've pushed 0.10.x with the lowercasing disabled for all but environment variables. 

---

I'd love to come back to this at some point and work on a refined API for v1.0 but I've been quite busy this year.
