### ISSUE TITLE
Support for ini files

### ISSUE THREAD

**Issue by vorner** [mehcode/config-rs#66]
Hello

Would it be possible to add a support for ini files? I know they are not as expressive as the other formats, but there may be reasons to want to work with them (like some other tools that produce/manage them and don't know anything better).

I was able to create a hacky solution for myself ‒ using the rust-ini crate, fill another `Config` instance and merge that as a source (and using keys with dots in them to refer to deeper levels), but a built-in would be nice. Though I don't know what to do with arrays properly.

**Comment by toyg** [comment]
Isn't this what #72 provides?

**Comment by vorner** [comment]
Yes, it seems so.

**Comment by mehcode** [comment]
This will be in the next release. Thanks @woodgear
