### ISSUE TITLE
Decide on a standard, default convention for configuration

### ISSUE THREAD

**Issue by mehcode** [mehcode/config-rs#7]
In the spirit of making this library easier to get into and use, I'm thinking we should recommend a convention for configuration (that could, of course, be disabled with feature flags).

1 - `./config` folder with `./config/default.toml` and `./config/{env}.toml`

```rust
config::merge(config::File::with_name("default").path("config"));
config::merge(config::File::with_name(env!("RUST_ENV")).path("config").required(false));
config::merge(config::Environment::new(""));
```

2 - `./Settings.toml` / `./Settings.{env}.toml`

```rust
config::merge(config::File::with_name("Settings"));
config::merge(config::File::with_name(&format!("Settings.{}", env!("RUST_ENV"))).required(false));
config::merge(config::Environment::new(""));
```

3 - `./Settings.toml` with namespaces

```rust
config::merge(config::File::with_name("Settings").namespace(env!("RUST_ENV")).required(false));
config::merge(config::Environment::new(""));
```

An example of 3:

```toml
[development]
debug = true

[production]
debug = false
```

---

 - This is using a unwritten feature of `config::File` to auto-detect the file type

---

The idea is that the equivalent of the above is done automatically. I'm partial to 3 but I'm open to other suggestions.

**Comment by tmccombs** [comment]
I think I prefer 1 or 2, because it makes it easy to have defaults specific overrides for different environments.

I also think it might be good to look in standard config directories for the platform, or at least have an easy way to do that (for example on linux search in the current directory, `$HOME/.config/appname` and `/etc/appname` in that order)

**Comment by ssokolow** [comment]
I'd start designing from [the approach that Qt's QSettings takes](https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes). That's about the best I've ever seen as a base design for a ready-made "just initialize and go" configuration store.

The TL;DR is that QSettings uses a four-step fallback chain which follows all platform conventions for where configurations should be stored:

1. Application-specific in the user profile
2. Vendor-specific in the user profile
3. Application-specific in the system-wide config store
4. Vendor-specific in the system-wide config store

(The "vendor-specific" referring to how configuration in QSettings is namespaced by vendor, and then by application, as is recommended for things like `~/.config/` and `HKEY_CURRENT_USER\Software`.)

**Comment by ayoshi** [comment]
Frankly, I gave it a lot of thought. I think the approach exhibited by clap is the best one to take: a series of builders (macroized or not) which allow to express a configuration as a rust object. Basically, clap is the configuration done through right through command line options. This approach has numerous benefits: 

1. It's easy to express in code (example)
2. It's file format independant (json, toml, yaml) can be used)
3. We can manipulate conflicting or dependent invariants, expressing them in code, disable or enable options (similar to required, requires, conflicts_with in clap) :
4. Default config file can be generated using a function, with comments from help text
5. I really like the merging approach you took. It allows for merging from environment or clap options.

```
let app_config = Config::new("My application")
                          .version("2.0") 
                          // we can support versioned config, the top version is the config file version
                          // .version set on options and sections let us express what version is supported
                          // Some options are available only up to version x
                          // Some appear only in version 2
                          // Will add [global] in .toml, or global { } in .json
                          .section(Section::with_name("global")
                                      // This section is added in config version 1.0
                                      // And will work in any config version older than 1.0
                                      .version("^1.0") 
                                      // The option will sit in section [global]
                                      .help("Global application settings")
                                      .setting(Setting::with_name("debug")
                                           // has a default which is set if option is not given
                                          .default(false)
                                          .help("Verbose debugging")))
                                          // Can be overriden with environment var DEBUG
                                          .env("DEBUG") 
                                           // Can be overriden with clap option --debug
                                          .clap_arg('debug')
                                           // Using wrong values will give error
                                          .possible_values(false,true)
                          .get_config();

//Load configuration file
app_config.merge_config_file("/etc/app_config.toml");
// Merge with environment
// Since we've specified ENV vars explicitely, only those will be overriden
app_config.merge_environment();
// Since we've specified clap_arg for some arguments, they will be overriden from command line
// Since we've specified clap_args explicitely, only those will be overriden
app_config_merge_with_clap(matches);
```

// Generate configuration file, if it's non existant - it will have default settings and comments
app_config.generate_default_config("/etc/app_config.toml", Format::Toml);
```

Something like that would be my dream configuration library.

**Comment by mehcode** [comment]
Love the suggestions.

---

I'm seeing two fundamental different bubbles for how a configuration library should operate.

An application designed to run by me/company and for me/company. Think a REST API, web service, or random script that is wrapped in a black box like a docker container. 

An application designed to run by a user that is not intimately familiar with its configuration. Think nginx, Atom, or spotify.

Let's call these two types of applications **inward** and **outward** -facing (towards its own developer(s) or towards the rest of the world).

For an inward-facing application I typically am writing a small API that is going to sit on a server for the next few years and not be looked at it. 
 - I want defaults so I can run this in development easily
 - I want overriding of that for a staging environment
 - I want overriding of that for a production environment (hopefully in a separate, secure location such as consul, etcd, or just a separate file with git-crypt).
 - I don't want to think about this too much.

```rust
extern crate config;
extern crate redis;

fn main() {
  let client = redis::Client::open(&config::get_str("redis")).unwrap();
}
```

I can definitely get behind a pre-defined configuration schema for an outward-facing application. Thinking of something things that would be very nice with this (mostly addressed with @ayoshi ):

 - Generating a file that contains default values
 - Upgrading configuration files
 - Helpful error messages when config values are weird or not what expected
 - Doesn't have much of a need of _remote_ configuration
 - **Editing** configuration files — Applications in this category sometimes evolve into fancy GUIs that allow editing of settings via UI. We can't say we support this use case without allowing write back in some fashion.

---

@tmccombs and @ssokolow — From what I understand this is _fallback_ and not _merging_, correct?

So something like this could work (if it was supported):

```rust
config::merge(config::File::with_name("settings").paths(&[
  "/etc/<appname>",
  "$HOME/config/appname",
  "$HOME/.appname"
]));
```

---

@ayoshi I like where you're going but I'm not a huge fan of the builder pattern when we get to this level of verbosity. How about ...

```rust
// Define schema
#[config("My Application", version = "2.1")]
struct AppConfig {
  #[setting(default = false)]
  /// Very verbose debugging information; trust me, you don't want this enabled.
  debug: bool,

  #[setting(default = "red", enum = ["red", "blue", "green"])]
  /// Primary color to make us look shiny
  color: String,
}

fn main() {
  // Prepare configuration source
  let f = config::File::with_name("settings").paths(&[
    "/etc/<appname>",
    "$HOME/config/appname",
    "$HOME/.appname"
  ]);

  // Merge as normal
  config::merge(f);
  config::merge(config::Environment::new(""));
  config::merge(config::Arguments(matches_from_clap));

  // Get configuration (using JSONPath to refer to root node to extract with this schema; but perhaps a better function name can be thought of to unmarshall the whole thing)
  let c = config::get::<AppConfig>("$");
  
  // Upgrade config at source
  c.upgrade(f);

  // Edit config at source
  c.set("debug", true);
  c.save(f);

  // Upgrade config at source
  c.generate(f);
}
```

That might be nice. However.. there is a lot of cross-over with the app description on clap-rs. Perhaps we could send a PR to clap-rs to allow fallback of its values to config "automatically" with a `config` feature. That might work out very cleanly for the kind of application I'm assuming you're doing.

**Comment by ssokolow** [comment]
What QSettings does can be described as merging at the file level, or fallback at the level of individual keys. (ie. It *is* merging, but the merging behaviour treats the contents of each key=value pair as opaque, so it'll override rather than append to or update vec/map values.)

Basically, it's a stack of overlays. If you were to extend the model to environment variables and command-line arguments, it would look something like this:

1. Is a value specified on the command-line? If not, keep looking.
2. Is a value specified via environment variable? If not, keep looking.
3. Is a value specified in `~/.config/VendorName/AppName.conf`? If not, keep looking.
4. Is a value specified in `~/.config/VendorName.conf`? If not, keep looking.
5. Is a value specified in `/etc/xdg/VendorName/AppName.conf`? If not, keep looking.
6. Is a value specified in `/etc/xdg/VendorName.conf`? If not, use a hard-coded default within the program.

**Comment by mehcode** [comment]
Arrays are currently treated as opaque but Maps get merged.
---
Then you could support this then today (except for the command-line part, we still need to implement the tie-in with clap but it shouldn't be too hard).

```rust
extern crate config;

use config::{File, FileFormat, Environment};

fn main() {
  config::merge(File::new("/etc/xdg/VendorName", FileFormat::Toml).required(false));
  config::merge(File::new("/etc/xdg/VendorName/AppName", FileFormat::Toml).required(false));
  // NOTE: We don't support env variables in the file name but I'm sold on adding it to v0.4
  config::merge(File::new("$HOME/.config/VendorName", FileFormat::Toml).required(false));
  config::merge(File::new("$HOME/.config/VendorName/AppName", FileFormat::Toml).required(false));

  // APPNAME_DEBUG would override a config property of "debug" 
  config::merge(Environment::new("AppName"));
}
```

Some additions that I want to get in by v0.4 to help:
 - Resolving environment variables in file paths
 - `File::with_name("AppName")` that would auto-detect the format based on the file extension

---

What I think I would do following your example:

```rust
extern crate config;

use config::{File, FileFormat, Environment};

fn main() {
  let mut s = File::new("settings", FileFormat::Toml).required(false);
  
  // /etc/appname/settings.toml
  config::merge(s.path("/etc/appname"));
  // $HOME/.config/appname/settings.toml
  config::merge(s.path("$HOME/.config/appname"));
  // $CWD/settings.toml
  config::merge(s);

  // APPNAME_DEBUG would override a config property of "debug" 
  config::merge(Environment::new("AppName"));
}
```

**Comment by ssokolow** [comment]
>  `// NOTE: We don't support env variables in the file name but I'm sold on adding it to v0.4`

Keep in mind that the actual correct behaviour in that use case is a bit more complex. In Bash syntax, it'd be `${XDG_CONFIG_HOME:-$HOME/.config}/VendorName/AppName`

(Use `$XDG_CONFIG_HOME` but pretend it's set to `$HOME/.config` if it's unset)

**Comment by retep998** [comment]
I have yet to see any mention of Windows. Please don't store configs in a dot directory in the home directory on Windows. Use AppData as it was meant to be used, in this case Roaming because you're storing configs.

**Comment by ssokolow** [comment]
The ideal solution would probably just be to use the [app_dirs](https://docs.rs/app_dirs/1.1.1/app_dirs/) crate for this particular case.

`app_dirs::get_app_root` will do the path lookup in a platform-aware manner very similar to what you get when you put `QSettings` in `IniFormat` mode to force non-Registry storage on Windows.

**Comment by mehcode** [comment]
@ssokolow / @retep998  Yeah. Perhaps we should leave it alone and let people just `format!` the config file with `app_dirs` or plain env variables themselves.

---

I think we've identified a number of areas where config can improve as a library. Thanks everyone. However I think I find myself re-thinking this issue, at least for now. I don't think there is a default set of configuration that can be agreed upon enough to be useful. We should just strive to make common use cases easier to use. And perhaps wrapper libraries that make it 1-line for a very common setup.

**Comment by whmountains** [comment]
> Perhaps we could send a PR to clap-rs to allow fallback of its values to config "automatically" with a config feature. 

This would be so nice!
