### ISSUE TITLE
[Question] Are special char in keys allowed?

### ISSUE THREAD

**Issue by mail6543210** [mehcode/config-rs#76]
I have a file containing keys with some symbols such as `@`, `#`, ..., etc.
And the `get_*()` returns `Err(IsA)`.

Are those characters supported in keys?

**Comment by mehcode** [comment]
Currently no. See: https://github.com/mehcode/config-rs/blob/master/src/path/parser.rs#L7-L11

The idea is that the keys are supposed to be rust identifiers. And any special syntax was reserved for future "magic" (perhaps `some_array_key#append` to throw out a random idea).
