### ISSUE TITLE
'watch' example doesn't run

### ISSUE THREAD

**Issue by danieleades** [mehcode/config-rs#77]
1. .serialize is deprecated (.serialize -> try_into)
2. panics at line 27 (cannot move out of borrowed content)

**Comment by danieleades** [comment]
could only get this to build by explicitly dereferencing and cloning the config struct

`SETTINGS.read().unwrap().deref().clone().try_into::<HashMap<String, String>>().unwrap();`

even then i don't see any updates when the settings file is modified.

**Comment by mehcode** [comment]
@danieleades What OS are you on? It could be an issue with the `notify` crate. Currently `config` doesn't provide any built-in file watching. 

I just tried it now on macOS 10.13 (after fixing the compile problems):

```
 * Settings ::
{"debug": "false", "port": "8080", "host": "0.0.0.0"}
 * Settings.toml written; refreshing configuration ...
 * Settings ::
{"port": "3223", "host": "0.0.0.0", "debug": "false"}
```

**Comment by mehcode** [comment]
Thanks for the research. That makes sense. I would like this lib to have built-in `.watch` at some point.
