### ISSUE TITLE
Support for File from Path

### ISSUE THREAD

**Issue by 0xpr03** [mehcode/config-rs#84]
I'm currently creating the config folder by myself and trying to write a default config if not existing (as this also includes comments etc). But I can't pass the path to config-rs and have to build the path twice, once for checking if existing & creation via absolute Path, once with relative str for config-rs Files.
A method like File::from_path() would be nice.

**Comment by robinkrahl** [comment]
`File` already implements [`From<&'_ Path>`](https://docs.rs/config/0.10.1/config/struct.File.html#impl-From%3C%26%27a%20Path%3E) and [`From<PathBuf>`](https://docs.rs/config/0.10.1/config/struct.File.html#impl-From%3CPathBuf%3E).  I think that’s everything you need for this use case.

**Comment by matthiasbeyer** [comment]
Is this issue still relevant/valid?

**Comment by 0xpr03** [comment]
I think so
