### ISSUE TITLE
Incorrect use of unsafe

### ISSUE THREAD

**Issue by dtolnay** [mehcode/config-rs#9]
Something is going wrong. I shouldn't be able to crash my program like this.

```rust
extern crate config;

fn main() {
    config::set_default("k", "----").unwrap();
    let v = config::get("k");
    config::set_default("k", "").unwrap();
    println!("{:?}", v);
}
```

Sometimes it reads corrupted memory:

```
Some(String("в©è"))
```

Sometimes it crashes:

```
thread 'main' panicked at 'byte index 5 is out of bounds of `вðO`'
```

```
thread 'main' panicked at 'byte index 3 is not a char boundary; it is inside '5' (bytes 2..3) of `Т5®`'
```

**Comment by mehcode** [comment]
@dtolnay You're right. I didn't think about this when I made the global API. The instance API works fine and has a compile error on the above.

```rust
extern crate config;

fn main() {
    let mut c = config::Config::new();
    c.set_default("k", "----").unwrap();
    let v = c.get("k");
    c.set_default("k", "").unwrap();
    println!("{:?}", v);
}
```

---

I'm welcome to suggestions on how to keep a global API and fix this issue. I'm still very new to Rust. I'll definitely look into fixing this very soon.

The cop-out solution is to automatically freeze configuration on the first `.get`. That's a bit too opinionated for this library though. I only mention it as I've seen other config libraries do it.

**Comment by dtolnay** [comment]
You have three options:

- Change the global API. I would strongly prefer this. See https://github.com/mehcode/config-rs/issues/8#issuecomment-279159276.

    ```rust
    pub fn get<T: Deserialize>(key: &str) -> Result<T, Error>
    ```

- Mark every destructive function (`set`, `set_default`, `merge` etc) as unsafe. Nobody would use this crate if they knew how recklessly unsafe it is.

- Freeze the global state on the first get. Too opinionated I agree.

**Comment by mehcode** [comment]
> Nobody would use this crate if they knew how recklessly unsafe it is.

Ouch. Keep in mind the crate has barely existed for 2 weeks.

---

Is there no way to propagate the lifetime so it behaves like the instance API?

**Comment by dtolnay** [comment]
> Ouch. Keep in mind the crate has barely existed for 2 weeks.

Sorry I added a :stuck_out_tongue_winking_eye: to show I meant it playfully. It's great to have caught this now rather than 3 months from now when this library is the wildly popular default way of handling config in Rust and it's hard to evolve the API without breaking the world.

> Is there no way to propagate the lifetime so it behaves like the instance API?

No, and this is why `static mut` is unsafe. The programmer is responsible for respecting the invariants by some other means than what is checked by the Rust compiler. [This forum thread](https://internals.rust-lang.org/t/pre-rfc-remove-static-mut/1437?u=dtolnay) discusses the situation in more detail.
