### ISSUE TITLE
Would be nice to support custom types

### ISSUE THREAD

**Issue by scuzzycheese** [mehcode/config-rs#92]
I see, you have a ValueKind, that had only a set number of types (unsigned types not included). It would be nice if one could provide your own implementation of some trait or something to return some sort of generic representation of a configuration value.

**Comment by robinkrahl** [comment]
Possible workaround: If you use [`Config::try_into`](https://docs.rs/config/0.10.1/config/struct.Config.html#method.try_into) to deserialize the configuration values into a struct, then the parsing is delegated to `serde` and you can derive or manually implement `serde::Deserialize` for your type.

**Comment by matthiasbeyer** [comment]
I assume this is solved with the last comment.
Feel free to reopen if this is not the case.

**Comment by pascaldanek** [comment]
Hello, I am currently trying to add custom types to my configuration. @robinkrahl could you elaborate on your proposal ? Am I suppose to write a `TryFrom<Config>` for my type, or is there some implicit serde deserialization that should occur ? A short example would be awesome ! Thanks for your help.

**Comment by robinkrahl** [comment]
@pascaldanek `Config::try_into` was renamed to `Config::try_deserialize`.  I don’t remember the details but I guess something like this should work:

```rust
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Config {
    foo: usize,
    bar: String,
}

fn main() {
    let config: Config = config::Config::builder()
        .add_source(...)
        .try_deserialize()
        .unwrap();
    println!("{:?}", config);
}
```

Now you can use all types implementing `serde::Deserialize` in `Config`.

**Comment by pascaldanek** [comment]
Thanks @robinkrahl , works like a charm :)
