### ISSUE TITLE
Hierarchical env support: can't make it work

### ISSUE THREAD

**Issue by pierre-l** [mehcode/config-rs#96]
Hi,

Because of the "hierarchical-env" example I was under the impression that I could use the following environment variable to set the database URL:

```
export APP_DATABASE_URL="postgres://test"
```

However I tried various combinations on a few properties and couldn't make this work. Is this supported?

**Comment by damiencollard** [comment]
You have to explicitly set the separator used in the env var, as it's None by default.
In your example, that would be `_`:
```
let mut s = config::Config::new();
s.merge(config::Environment::with_prefix("APP").separator("_"));
```

**Comment by pierre-l** [comment]
I missed that! Everything now works as I expected.

I still have a couple of other requirements to check but this crate looks great and I appreciate it a lot. I'll try to make a PR in order to avoid any future issue on this topic.

Thank you a lot!
