### ISSUE TITLE
Expose value origin

### ISSUE THREAD

**Issue by aes** [mehcode/config-rs#97]
It could be as simple as adding "pub", but it should probably be hidden in an accessor.

    -    origin: Option<String>,
    +    pub origin: Option<String>,

(this is what I do now, to move forward with what I'm doing)

I can see a case for making it a thing that needs to be enabled, (elided at run-time by default) or require the use of a different type, (elided at compile-time, by default) but not having _any_ way to figure out where a value comes from isn't working for me.

**Comment by ereOn** [comment]
This would actually allow us to provide context when reading relative paths and allow us to make those absolute, relative to the file that contained them.

It'd probably be even better if the origin wasn't a simple `Option<String>` but an enum type of sorts, allowing us to quickly determine the kind of source for a configuration value (file, environment, remote, ...). But I suspect this might be a bigger change. Exposing the origin would already be a huge improvement.

**Comment by martinvonz** [comment]
When this gets implemented, it will probably also make sense to be able to set the origin when you create an in-memory `Config` object and when you set overrides.

The use case I have is to be able to implement something like `git config --show-origin`, where there application can set e.g. the origin to e.g. "GIT_EDITOR"  or "environment" when it sets the value of `core.editor` based on the `$GIT_EDITOR` environment variable (although it seems git doesn't actually do it that way internally -- `GIT_EDITOR=foo git config --show-origin core.editor` doesn't show "foo").

Let me know if you prefer that I move this request to a separate issue.

**Comment by matthiasbeyer** [comment]
Would #318 be what you'd like to see?

**Comment by martinvonz** [comment]
It looks like that addresses OP's request, but not the addition I wanted, right? I'm happy to move my additional request to a separate issue.

**Comment by matthiasbeyer** [comment]
Yes please do that! :smile:
